# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""AccountConfigUpdate_200_response_result

    AccountConfigUpdate200ResponseResult(;
        updated_items=nothing,
    )

    - updated_items::Int64
"""
Base.@kwdef mutable struct AccountConfigUpdate200ResponseResult <: OpenAPI.APIModel
    updated_items::Union{Nothing, Int64} = nothing

    function AccountConfigUpdate200ResponseResult(updated_items, )
        OpenAPI.validate_property(AccountConfigUpdate200ResponseResult, Symbol("updated_items"), updated_items)
        return new(updated_items, )
    end
end # type AccountConfigUpdate200ResponseResult

const _property_types_AccountConfigUpdate200ResponseResult = Dict{Symbol,String}(Symbol("updated_items")=>"Int64", )
OpenAPI.property_type(::Type{ AccountConfigUpdate200ResponseResult }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_AccountConfigUpdate200ResponseResult[name]))}

function check_required(o::AccountConfigUpdate200ResponseResult)
    true
end

function OpenAPI.validate_property(::Type{ AccountConfigUpdate200ResponseResult }, name::Symbol, val)

end
