# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""CategoryAdd_200_response_result

    CategoryAdd200ResponseResult(;
        category_id=nothing,
    )

    - category_id::String
"""
Base.@kwdef mutable struct CategoryAdd200ResponseResult <: OpenAPI.APIModel
    category_id::Union{Nothing, String} = nothing

    function CategoryAdd200ResponseResult(category_id, )
        OpenAPI.validate_property(CategoryAdd200ResponseResult, Symbol("category_id"), category_id)
        return new(category_id, )
    end
end # type CategoryAdd200ResponseResult

const _property_types_CategoryAdd200ResponseResult = Dict{Symbol,String}(Symbol("category_id")=>"String", )
OpenAPI.property_type(::Type{ CategoryAdd200ResponseResult }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_CategoryAdd200ResponseResult[name]))}

function check_required(o::CategoryAdd200ResponseResult)
    true
end

function OpenAPI.validate_property(::Type{ CategoryAdd200ResponseResult }, name::Symbol, val)

end
