# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""Model_Response_Order_FulfillmentStatus_List

    ModelResponseOrderFulfillmentStatusList(;
        return_code=nothing,
        return_message=nothing,
        result=nothing,
        additional_fields=nothing,
        custom_fields=nothing,
    )

    - return_code::Int64
    - return_message::String
    - result::ResponseOrderFulfillmentStatusListResult
    - additional_fields::Any
    - custom_fields::Any
"""
Base.@kwdef mutable struct ModelResponseOrderFulfillmentStatusList <: OpenAPI.APIModel
    return_code::Union{Nothing, Int64} = nothing
    return_message::Union{Nothing, String} = nothing
    result = nothing # spec type: Union{ Nothing, ResponseOrderFulfillmentStatusListResult }
    additional_fields::Union{Nothing, Any} = nothing
    custom_fields::Union{Nothing, Any} = nothing

    function ModelResponseOrderFulfillmentStatusList(return_code, return_message, result, additional_fields, custom_fields, )
        OpenAPI.validate_property(ModelResponseOrderFulfillmentStatusList, Symbol("return_code"), return_code)
        OpenAPI.validate_property(ModelResponseOrderFulfillmentStatusList, Symbol("return_message"), return_message)
        OpenAPI.validate_property(ModelResponseOrderFulfillmentStatusList, Symbol("result"), result)
        OpenAPI.validate_property(ModelResponseOrderFulfillmentStatusList, Symbol("additional_fields"), additional_fields)
        OpenAPI.validate_property(ModelResponseOrderFulfillmentStatusList, Symbol("custom_fields"), custom_fields)
        return new(return_code, return_message, result, additional_fields, custom_fields, )
    end
end # type ModelResponseOrderFulfillmentStatusList

const _property_types_ModelResponseOrderFulfillmentStatusList = Dict{Symbol,String}(Symbol("return_code")=>"Int64", Symbol("return_message")=>"String", Symbol("result")=>"ResponseOrderFulfillmentStatusListResult", Symbol("additional_fields")=>"Any", Symbol("custom_fields")=>"Any", )
OpenAPI.property_type(::Type{ ModelResponseOrderFulfillmentStatusList }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ModelResponseOrderFulfillmentStatusList[name]))}

function check_required(o::ModelResponseOrderFulfillmentStatusList)
    true
end

function OpenAPI.validate_property(::Type{ ModelResponseOrderFulfillmentStatusList }, name::Symbol, val)





end
