# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""Language

    Language(;
        id=nothing,
        iso_code=nothing,
        name=nothing,
        additional_fields=nothing,
        custom_fields=nothing,
    )

    - id::String
    - iso_code::String
    - name::String
    - additional_fields::Any
    - custom_fields::Any
"""
Base.@kwdef mutable struct Language <: OpenAPI.APIModel
    id::Union{Nothing, String} = nothing
    iso_code::Union{Nothing, String} = nothing
    name::Union{Nothing, String} = nothing
    additional_fields::Union{Nothing, Any} = nothing
    custom_fields::Union{Nothing, Any} = nothing

    function Language(id, iso_code, name, additional_fields, custom_fields, )
        OpenAPI.validate_property(Language, Symbol("id"), id)
        OpenAPI.validate_property(Language, Symbol("iso_code"), iso_code)
        OpenAPI.validate_property(Language, Symbol("name"), name)
        OpenAPI.validate_property(Language, Symbol("additional_fields"), additional_fields)
        OpenAPI.validate_property(Language, Symbol("custom_fields"), custom_fields)
        return new(id, iso_code, name, additional_fields, custom_fields, )
    end
end # type Language

const _property_types_Language = Dict{Symbol,String}(Symbol("id")=>"String", Symbol("iso_code")=>"String", Symbol("name")=>"String", Symbol("additional_fields")=>"Any", Symbol("custom_fields")=>"Any", )
OpenAPI.property_type(::Type{ Language }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_Language[name]))}

function check_required(o::Language)
    true
end

function OpenAPI.validate_property(::Type{ Language }, name::Symbol, val)





end
