# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""AttributeAssignGroup_200_response_result

    AttributeAssignGroup200ResponseResult(;
        assigned=nothing,
    )

    - assigned::String
"""
Base.@kwdef mutable struct AttributeAssignGroup200ResponseResult <: OpenAPI.APIModel
    assigned::Union{Nothing, String} = nothing

    function AttributeAssignGroup200ResponseResult(assigned, )
        OpenAPI.validate_property(AttributeAssignGroup200ResponseResult, Symbol("assigned"), assigned)
        return new(assigned, )
    end
end # type AttributeAssignGroup200ResponseResult

const _property_types_AttributeAssignGroup200ResponseResult = Dict{Symbol,String}(Symbol("assigned")=>"String", )
OpenAPI.property_type(::Type{ AttributeAssignGroup200ResponseResult }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_AttributeAssignGroup200ResponseResult[name]))}

function check_required(o::AttributeAssignGroup200ResponseResult)
    true
end

function OpenAPI.validate_property(::Type{ AttributeAssignGroup200ResponseResult }, name::Symbol, val)

end
