# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ProductAdd_certifications_inner_files_inner

    ProductAddCertificationsInnerFilesInner(;
        url=nothing,
    )

    - url::String : File URL
"""
Base.@kwdef mutable struct ProductAddCertificationsInnerFilesInner <: OpenAPI.APIModel
    url::Union{Nothing, String} = nothing

    function ProductAddCertificationsInnerFilesInner(url, )
        OpenAPI.validate_property(ProductAddCertificationsInnerFilesInner, Symbol("url"), url)
        return new(url, )
    end
end # type ProductAddCertificationsInnerFilesInner

const _property_types_ProductAddCertificationsInnerFilesInner = Dict{Symbol,String}(Symbol("url")=>"String", )
OpenAPI.property_type(::Type{ ProductAddCertificationsInnerFilesInner }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ProductAddCertificationsInnerFilesInner[name]))}

function check_required(o::ProductAddCertificationsInnerFilesInner)
    o.url === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ ProductAddCertificationsInnerFilesInner }, name::Symbol, val)

end
