# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ProductVariantDeleteBatch

    ProductVariantDeleteBatch(;
        clear_cache=false,
        reindex=false,
        payload=nothing,
    )

    - clear_cache::Bool
    - reindex::Bool
    - payload::Vector{ProductVariantDeleteBatchPayloadInner} : Contains an array of product variant deletion requests, each including the product ID and variant ID. The list of properties may vary depending on the specific platform.
"""
Base.@kwdef mutable struct ProductVariantDeleteBatch <: OpenAPI.APIModel
    clear_cache::Union{Nothing, Bool} = false
    reindex::Union{Nothing, Bool} = false
    payload::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{ProductVariantDeleteBatchPayloadInner} }

    function ProductVariantDeleteBatch(clear_cache, reindex, payload, )
        OpenAPI.validate_property(ProductVariantDeleteBatch, Symbol("clear_cache"), clear_cache)
        OpenAPI.validate_property(ProductVariantDeleteBatch, Symbol("reindex"), reindex)
        OpenAPI.validate_property(ProductVariantDeleteBatch, Symbol("payload"), payload)
        return new(clear_cache, reindex, payload, )
    end
end # type ProductVariantDeleteBatch

const _property_types_ProductVariantDeleteBatch = Dict{Symbol,String}(Symbol("clear_cache")=>"Bool", Symbol("reindex")=>"Bool", Symbol("payload")=>"Vector{ProductVariantDeleteBatchPayloadInner}", )
OpenAPI.property_type(::Type{ ProductVariantDeleteBatch }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ProductVariantDeleteBatch[name]))}

function check_required(o::ProductVariantDeleteBatch)
    o.payload === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ ProductVariantDeleteBatch }, name::Symbol, val)



    if name === Symbol("payload")
        OpenAPI.validate_param(name, "ProductVariantDeleteBatch", :maxItems, val, 250)
        OpenAPI.validate_param(name, "ProductVariantDeleteBatch", :minItems, val, 1)
    end
end
