# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""CartDelete_200_response_result

    CartDelete200ResponseResult(;
        store=nothing,
    )

    - store::String
"""
Base.@kwdef mutable struct CartDelete200ResponseResult <: OpenAPI.APIModel
    store::Union{Nothing, String} = nothing

    function CartDelete200ResponseResult(store, )
        OpenAPI.validate_property(CartDelete200ResponseResult, Symbol("store"), store)
        return new(store, )
    end
end # type CartDelete200ResponseResult

const _property_types_CartDelete200ResponseResult = Dict{Symbol,String}(Symbol("store")=>"String", )
OpenAPI.property_type(::Type{ CartDelete200ResponseResult }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_CartDelete200ResponseResult[name]))}

function check_required(o::CartDelete200ResponseResult)
    true
end

function OpenAPI.validate_property(::Type{ CartDelete200ResponseResult }, name::Symbol, val)

end
