# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""CartCouponCount_200_response_result

    CartCouponCount200ResponseResult(;
        coupons_count=nothing,
    )

    - coupons_count::String
"""
Base.@kwdef mutable struct CartCouponCount200ResponseResult <: OpenAPI.APIModel
    coupons_count::Union{Nothing, String} = nothing

    function CartCouponCount200ResponseResult(coupons_count, )
        OpenAPI.validate_property(CartCouponCount200ResponseResult, Symbol("coupons_count"), coupons_count)
        return new(coupons_count, )
    end
end # type CartCouponCount200ResponseResult

const _property_types_CartCouponCount200ResponseResult = Dict{Symbol,String}(Symbol("coupons_count")=>"String", )
OpenAPI.property_type(::Type{ CartCouponCount200ResponseResult }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_CartCouponCount200ResponseResult[name]))}

function check_required(o::CartCouponCount200ResponseResult)
    true
end

function OpenAPI.validate_property(::Type{ CartCouponCount200ResponseResult }, name::Symbol, val)

end
