# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""CustomerCount_200_response_result

    CustomerCount200ResponseResult(;
        customers_count=nothing,
    )

    - customers_count::Int64
"""
Base.@kwdef mutable struct CustomerCount200ResponseResult <: OpenAPI.APIModel
    customers_count::Union{Nothing, Int64} = nothing

    function CustomerCount200ResponseResult(customers_count, )
        OpenAPI.validate_property(CustomerCount200ResponseResult, Symbol("customers_count"), customers_count)
        return new(customers_count, )
    end
end # type CustomerCount200ResponseResult

const _property_types_CustomerCount200ResponseResult = Dict{Symbol,String}(Symbol("customers_count")=>"Int64", )
OpenAPI.property_type(::Type{ CustomerCount200ResponseResult }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_CustomerCount200ResponseResult[name]))}

function check_required(o::CustomerCount200ResponseResult)
    true
end

function OpenAPI.validate_property(::Type{ CustomerCount200ResponseResult }, name::Symbol, val)

end
