# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""CustomerUpdate

    CustomerUpdate(;
        id=nothing,
        group_id=nothing,
        group_ids=nothing,
        group=nothing,
        email=nothing,
        phone=nothing,
        first_name=nothing,
        last_name=nothing,
        birth_day=nothing,
        news_letter_subscription=nothing,
        consents=nothing,
        tags=nothing,
        gender=nothing,
        note=nothing,
        status=nothing,
        password=nothing,
        currency_id=nothing,
        company=nothing,
        country=nothing,
        fax=nothing,
        tax_id=nothing,
        is_tax_exempt=nothing,
        vendor_id=nothing,
        store_id=nothing,
        idempotency_key=nothing,
        address=nothing,
    )

    - id::String : Entity id
    - group_id::String : Customer group_id
    - group_ids::String : Groups that will be assigned to a customer
    - group::String : Defines the group where the customer
    - email::String : Defines customer&#39;s email
    - phone::String : Defines customer&#39;s phone number
    - first_name::String : Defines customer&#39;s first name
    - last_name::String : Defines customer&#39;s last name
    - birth_day::String : Defines customer&#39;s birthday
    - news_letter_subscription::Bool : Defines whether the newsletter subscription is available for the user
    - consents::Vector{CustomerAddConsentsInner} : Defines consents to notifications
    - tags::String : Customer tags
    - gender::String : Defines customer&#39;s gender
    - note::String : The customer note.
    - status::String : Defines customer&#39;s status
    - password::String : Defines customer&#39;s unique password
    - currency_id::String : Currency Id
    - company::String : Defines customer&#39;s company
    - country::String : Specifies ISO code or name of country
    - fax::String : Defines customer&#39;s fax
    - tax_id::String : Add Tax Id
    - is_tax_exempt::Bool : Marks a customer as tax-exempt (B2B/wholesale).
    - vendor_id::String : Updates vendor id of the customer
    - store_id::String : Store Id
    - idempotency_key::String : A unique identifier associated with a specific request. Repeated requests with the same &lt;strong&gt;idempotency_key&lt;/strong&gt; return a cached response without re-executing the business logic. &lt;strong&gt;Please note that the cache lifetime is 15 minutes.&lt;/strong&gt;
    - address::Vector{CustomerUpdateAddressInner}
"""
Base.@kwdef mutable struct CustomerUpdate <: OpenAPI.APIModel
    id::Union{Nothing, String} = nothing
    group_id::Union{Nothing, String} = nothing
    group_ids::Union{Nothing, String} = nothing
    group::Union{Nothing, String} = nothing
    email::Union{Nothing, String} = nothing
    phone::Union{Nothing, String} = nothing
    first_name::Union{Nothing, String} = nothing
    last_name::Union{Nothing, String} = nothing
    birth_day::Union{Nothing, String} = nothing
    news_letter_subscription::Union{Nothing, Bool} = nothing
    consents::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{CustomerAddConsentsInner} }
    tags::Union{Nothing, String} = nothing
    gender::Union{Nothing, String} = nothing
    note::Union{Nothing, String} = nothing
    status::Union{Nothing, String} = nothing
    password::Union{Nothing, String} = nothing
    currency_id::Union{Nothing, String} = nothing
    company::Union{Nothing, String} = nothing
    country::Union{Nothing, String} = nothing
    fax::Union{Nothing, String} = nothing
    tax_id::Union{Nothing, String} = nothing
    is_tax_exempt::Union{Nothing, Bool} = nothing
    vendor_id::Union{Nothing, String} = nothing
    store_id::Union{Nothing, String} = nothing
    idempotency_key::Union{Nothing, String} = nothing
    address::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{CustomerUpdateAddressInner} }

    function CustomerUpdate(id, group_id, group_ids, group, email, phone, first_name, last_name, birth_day, news_letter_subscription, consents, tags, gender, note, status, password, currency_id, company, country, fax, tax_id, is_tax_exempt, vendor_id, store_id, idempotency_key, address, )
        OpenAPI.validate_property(CustomerUpdate, Symbol("id"), id)
        OpenAPI.validate_property(CustomerUpdate, Symbol("group_id"), group_id)
        OpenAPI.validate_property(CustomerUpdate, Symbol("group_ids"), group_ids)
        OpenAPI.validate_property(CustomerUpdate, Symbol("group"), group)
        OpenAPI.validate_property(CustomerUpdate, Symbol("email"), email)
        OpenAPI.validate_property(CustomerUpdate, Symbol("phone"), phone)
        OpenAPI.validate_property(CustomerUpdate, Symbol("first_name"), first_name)
        OpenAPI.validate_property(CustomerUpdate, Symbol("last_name"), last_name)
        OpenAPI.validate_property(CustomerUpdate, Symbol("birth_day"), birth_day)
        OpenAPI.validate_property(CustomerUpdate, Symbol("news_letter_subscription"), news_letter_subscription)
        OpenAPI.validate_property(CustomerUpdate, Symbol("consents"), consents)
        OpenAPI.validate_property(CustomerUpdate, Symbol("tags"), tags)
        OpenAPI.validate_property(CustomerUpdate, Symbol("gender"), gender)
        OpenAPI.validate_property(CustomerUpdate, Symbol("note"), note)
        OpenAPI.validate_property(CustomerUpdate, Symbol("status"), status)
        OpenAPI.validate_property(CustomerUpdate, Symbol("password"), password)
        OpenAPI.validate_property(CustomerUpdate, Symbol("currency_id"), currency_id)
        OpenAPI.validate_property(CustomerUpdate, Symbol("company"), company)
        OpenAPI.validate_property(CustomerUpdate, Symbol("country"), country)
        OpenAPI.validate_property(CustomerUpdate, Symbol("fax"), fax)
        OpenAPI.validate_property(CustomerUpdate, Symbol("tax_id"), tax_id)
        OpenAPI.validate_property(CustomerUpdate, Symbol("is_tax_exempt"), is_tax_exempt)
        OpenAPI.validate_property(CustomerUpdate, Symbol("vendor_id"), vendor_id)
        OpenAPI.validate_property(CustomerUpdate, Symbol("store_id"), store_id)
        OpenAPI.validate_property(CustomerUpdate, Symbol("idempotency_key"), idempotency_key)
        OpenAPI.validate_property(CustomerUpdate, Symbol("address"), address)
        return new(id, group_id, group_ids, group, email, phone, first_name, last_name, birth_day, news_letter_subscription, consents, tags, gender, note, status, password, currency_id, company, country, fax, tax_id, is_tax_exempt, vendor_id, store_id, idempotency_key, address, )
    end
end # type CustomerUpdate

const _property_types_CustomerUpdate = Dict{Symbol,String}(Symbol("id")=>"String", Symbol("group_id")=>"String", Symbol("group_ids")=>"String", Symbol("group")=>"String", Symbol("email")=>"String", Symbol("phone")=>"String", Symbol("first_name")=>"String", Symbol("last_name")=>"String", Symbol("birth_day")=>"String", Symbol("news_letter_subscription")=>"Bool", Symbol("consents")=>"Vector{CustomerAddConsentsInner}", Symbol("tags")=>"String", Symbol("gender")=>"String", Symbol("note")=>"String", Symbol("status")=>"String", Symbol("password")=>"String", Symbol("currency_id")=>"String", Symbol("company")=>"String", Symbol("country")=>"String", Symbol("fax")=>"String", Symbol("tax_id")=>"String", Symbol("is_tax_exempt")=>"Bool", Symbol("vendor_id")=>"String", Symbol("store_id")=>"String", Symbol("idempotency_key")=>"String", Symbol("address")=>"Vector{CustomerUpdateAddressInner}", )
OpenAPI.property_type(::Type{ CustomerUpdate }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_CustomerUpdate[name]))}

function check_required(o::CustomerUpdate)
    true
end

function OpenAPI.validate_property(::Type{ CustomerUpdate }, name::Symbol, val)











    if name === Symbol("consents")
        OpenAPI.validate_param(name, "CustomerUpdate", :minItems, val, 1)
    end















end
