# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""Cart_ShippingMethod_Rate

    CartShippingMethodRate(;
        min_weight=nothing,
        max_weight=nothing,
        min_order_amount=nothing,
        max_order_amount=nothing,
        min_items_count=nothing,
        max_items_count=nothing,
        price=nothing,
        additional_fields=nothing,
        custom_fields=nothing,
    )

    - min_weight::String
    - max_weight::String
    - min_order_amount::String
    - max_order_amount::String
    - min_items_count::String
    - max_items_count::String
    - price::String
    - additional_fields::Any
    - custom_fields::Any
"""
Base.@kwdef mutable struct CartShippingMethodRate <: OpenAPI.APIModel
    min_weight::Union{Nothing, String} = nothing
    max_weight::Union{Nothing, String} = nothing
    min_order_amount::Union{Nothing, String} = nothing
    max_order_amount::Union{Nothing, String} = nothing
    min_items_count::Union{Nothing, String} = nothing
    max_items_count::Union{Nothing, String} = nothing
    price::Union{Nothing, String} = nothing
    additional_fields::Union{Nothing, Any} = nothing
    custom_fields::Union{Nothing, Any} = nothing

    function CartShippingMethodRate(min_weight, max_weight, min_order_amount, max_order_amount, min_items_count, max_items_count, price, additional_fields, custom_fields, )
        OpenAPI.validate_property(CartShippingMethodRate, Symbol("min_weight"), min_weight)
        OpenAPI.validate_property(CartShippingMethodRate, Symbol("max_weight"), max_weight)
        OpenAPI.validate_property(CartShippingMethodRate, Symbol("min_order_amount"), min_order_amount)
        OpenAPI.validate_property(CartShippingMethodRate, Symbol("max_order_amount"), max_order_amount)
        OpenAPI.validate_property(CartShippingMethodRate, Symbol("min_items_count"), min_items_count)
        OpenAPI.validate_property(CartShippingMethodRate, Symbol("max_items_count"), max_items_count)
        OpenAPI.validate_property(CartShippingMethodRate, Symbol("price"), price)
        OpenAPI.validate_property(CartShippingMethodRate, Symbol("additional_fields"), additional_fields)
        OpenAPI.validate_property(CartShippingMethodRate, Symbol("custom_fields"), custom_fields)
        return new(min_weight, max_weight, min_order_amount, max_order_amount, min_items_count, max_items_count, price, additional_fields, custom_fields, )
    end
end # type CartShippingMethodRate

const _property_types_CartShippingMethodRate = Dict{Symbol,String}(Symbol("min_weight")=>"String", Symbol("max_weight")=>"String", Symbol("min_order_amount")=>"String", Symbol("max_order_amount")=>"String", Symbol("min_items_count")=>"String", Symbol("max_items_count")=>"String", Symbol("price")=>"String", Symbol("additional_fields")=>"Any", Symbol("custom_fields")=>"Any", )
OpenAPI.property_type(::Type{ CartShippingMethodRate }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_CartShippingMethodRate[name]))}

function check_required(o::CartShippingMethodRate)
    true
end

function OpenAPI.validate_property(::Type{ CartShippingMethodRate }, name::Symbol, val)









end
