# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""Response_Order_Count_Result

    ResponseOrderCountResult(;
        orders_count=nothing,
        additional_fields=nothing,
        custom_fields=nothing,
    )

    - orders_count::Int64
    - additional_fields::Any
    - custom_fields::Any
"""
Base.@kwdef mutable struct ResponseOrderCountResult <: OpenAPI.APIModel
    orders_count::Union{Nothing, Int64} = nothing
    additional_fields::Union{Nothing, Any} = nothing
    custom_fields::Union{Nothing, Any} = nothing

    function ResponseOrderCountResult(orders_count, additional_fields, custom_fields, )
        OpenAPI.validate_property(ResponseOrderCountResult, Symbol("orders_count"), orders_count)
        OpenAPI.validate_property(ResponseOrderCountResult, Symbol("additional_fields"), additional_fields)
        OpenAPI.validate_property(ResponseOrderCountResult, Symbol("custom_fields"), custom_fields)
        return new(orders_count, additional_fields, custom_fields, )
    end
end # type ResponseOrderCountResult

const _property_types_ResponseOrderCountResult = Dict{Symbol,String}(Symbol("orders_count")=>"Int64", Symbol("additional_fields")=>"Any", Symbol("custom_fields")=>"Any", )
OpenAPI.property_type(::Type{ ResponseOrderCountResult }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ResponseOrderCountResult[name]))}

function check_required(o::ResponseOrderCountResult)
    true
end

function OpenAPI.validate_property(::Type{ ResponseOrderCountResult }, name::Symbol, val)



end
