# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""Order_Calculate_Bundle

    OrderCalculateBundle(;
        product_id=nothing,
        sku=nothing,
        name=nothing,
        quantity=nothing,
        price=nothing,
        price_inc_tax=nothing,
        tax_rate=nothing,
        unit_discount=nothing,
        weight=nothing,
        weight_unit=nothing,
        barcode=nothing,
        variant_id=nothing,
        options=nothing,
        additional_fields=nothing,
        custom_fields=nothing,
    )

    - product_id::String
    - sku::String
    - name::String
    - quantity::Int64
    - price::Float64
    - price_inc_tax::Float64
    - tax_rate::Float64
    - unit_discount::Float64
    - weight::Float64
    - weight_unit::String
    - barcode::String
    - variant_id::String
    - options::Vector{OrderItemOption}
    - additional_fields::Any
    - custom_fields::Any
"""
Base.@kwdef mutable struct OrderCalculateBundle <: OpenAPI.APIModel
    product_id::Union{Nothing, String} = nothing
    sku::Union{Nothing, String} = nothing
    name::Union{Nothing, String} = nothing
    quantity::Union{Nothing, Int64} = nothing
    price::Union{Nothing, Float64} = nothing
    price_inc_tax::Union{Nothing, Float64} = nothing
    tax_rate::Union{Nothing, Float64} = nothing
    unit_discount::Union{Nothing, Float64} = nothing
    weight::Union{Nothing, Float64} = nothing
    weight_unit::Union{Nothing, String} = nothing
    barcode::Union{Nothing, String} = nothing
    variant_id::Union{Nothing, String} = nothing
    options::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{OrderItemOption} }
    additional_fields::Union{Nothing, Any} = nothing
    custom_fields::Union{Nothing, Any} = nothing

    function OrderCalculateBundle(product_id, sku, name, quantity, price, price_inc_tax, tax_rate, unit_discount, weight, weight_unit, barcode, variant_id, options, additional_fields, custom_fields, )
        OpenAPI.validate_property(OrderCalculateBundle, Symbol("product_id"), product_id)
        OpenAPI.validate_property(OrderCalculateBundle, Symbol("sku"), sku)
        OpenAPI.validate_property(OrderCalculateBundle, Symbol("name"), name)
        OpenAPI.validate_property(OrderCalculateBundle, Symbol("quantity"), quantity)
        OpenAPI.validate_property(OrderCalculateBundle, Symbol("price"), price)
        OpenAPI.validate_property(OrderCalculateBundle, Symbol("price_inc_tax"), price_inc_tax)
        OpenAPI.validate_property(OrderCalculateBundle, Symbol("tax_rate"), tax_rate)
        OpenAPI.validate_property(OrderCalculateBundle, Symbol("unit_discount"), unit_discount)
        OpenAPI.validate_property(OrderCalculateBundle, Symbol("weight"), weight)
        OpenAPI.validate_property(OrderCalculateBundle, Symbol("weight_unit"), weight_unit)
        OpenAPI.validate_property(OrderCalculateBundle, Symbol("barcode"), barcode)
        OpenAPI.validate_property(OrderCalculateBundle, Symbol("variant_id"), variant_id)
        OpenAPI.validate_property(OrderCalculateBundle, Symbol("options"), options)
        OpenAPI.validate_property(OrderCalculateBundle, Symbol("additional_fields"), additional_fields)
        OpenAPI.validate_property(OrderCalculateBundle, Symbol("custom_fields"), custom_fields)
        return new(product_id, sku, name, quantity, price, price_inc_tax, tax_rate, unit_discount, weight, weight_unit, barcode, variant_id, options, additional_fields, custom_fields, )
    end
end # type OrderCalculateBundle

const _property_types_OrderCalculateBundle = Dict{Symbol,String}(Symbol("product_id")=>"String", Symbol("sku")=>"String", Symbol("name")=>"String", Symbol("quantity")=>"Int64", Symbol("price")=>"Float64", Symbol("price_inc_tax")=>"Float64", Symbol("tax_rate")=>"Float64", Symbol("unit_discount")=>"Float64", Symbol("weight")=>"Float64", Symbol("weight_unit")=>"String", Symbol("barcode")=>"String", Symbol("variant_id")=>"String", Symbol("options")=>"Vector{OrderItemOption}", Symbol("additional_fields")=>"Any", Symbol("custom_fields")=>"Any", )
OpenAPI.property_type(::Type{ OrderCalculateBundle }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_OrderCalculateBundle[name]))}

function check_required(o::OrderCalculateBundle)
    true
end

function OpenAPI.validate_property(::Type{ OrderCalculateBundle }, name::Symbol, val)















end
