# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""A2CDateTime

    A2CDateTime(;
        value=nothing,
        format=nothing,
        additional_fields=nothing,
        custom_fields=nothing,
    )

    - value::String
    - format::String
    - additional_fields::Any
    - custom_fields::Any
"""
Base.@kwdef mutable struct A2CDateTime <: OpenAPI.APIModel
    value::Union{Nothing, String} = nothing
    format::Union{Nothing, String} = nothing
    additional_fields::Union{Nothing, Any} = nothing
    custom_fields::Union{Nothing, Any} = nothing

    function A2CDateTime(value, format, additional_fields, custom_fields, )
        OpenAPI.validate_property(A2CDateTime, Symbol("value"), value)
        OpenAPI.validate_property(A2CDateTime, Symbol("format"), format)
        OpenAPI.validate_property(A2CDateTime, Symbol("additional_fields"), additional_fields)
        OpenAPI.validate_property(A2CDateTime, Symbol("custom_fields"), custom_fields)
        return new(value, format, additional_fields, custom_fields, )
    end
end # type A2CDateTime

const _property_types_A2CDateTime = Dict{Symbol,String}(Symbol("value")=>"String", Symbol("format")=>"String", Symbol("additional_fields")=>"Any", Symbol("custom_fields")=>"Any", )
OpenAPI.property_type(::Type{ A2CDateTime }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_A2CDateTime[name]))}

function check_required(o::A2CDateTime)
    true
end

function OpenAPI.validate_property(::Type{ A2CDateTime }, name::Symbol, val)




end
