# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""AttributeUnassignGroup_200_response_result

    AttributeUnassignGroup200ResponseResult(;
        unassigned=nothing,
    )

    - unassigned::String
"""
Base.@kwdef mutable struct AttributeUnassignGroup200ResponseResult <: OpenAPI.APIModel
    unassigned::Union{Nothing, String} = nothing

    function AttributeUnassignGroup200ResponseResult(unassigned, )
        OpenAPI.validate_property(AttributeUnassignGroup200ResponseResult, Symbol("unassigned"), unassigned)
        return new(unassigned, )
    end
end # type AttributeUnassignGroup200ResponseResult

const _property_types_AttributeUnassignGroup200ResponseResult = Dict{Symbol,String}(Symbol("unassigned")=>"String", )
OpenAPI.property_type(::Type{ AttributeUnassignGroup200ResponseResult }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_AttributeUnassignGroup200ResponseResult[name]))}

function check_required(o::AttributeUnassignGroup200ResponseResult)
    true
end

function OpenAPI.validate_property(::Type{ AttributeUnassignGroup200ResponseResult }, name::Symbol, val)

end
