# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""Response_Customer_Find_Result

    ResponseCustomerFindResult(;
        customers_count=nothing,
        customer=nothing,
        additional_fields=nothing,
        custom_fields=nothing,
    )

    - customers_count::Int64
    - customer::Vector{Customer}
    - additional_fields::Any
    - custom_fields::Any
"""
Base.@kwdef mutable struct ResponseCustomerFindResult <: OpenAPI.APIModel
    customers_count::Union{Nothing, Int64} = nothing
    customer::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{Customer} }
    additional_fields::Union{Nothing, Any} = nothing
    custom_fields::Union{Nothing, Any} = nothing

    function ResponseCustomerFindResult(customers_count, customer, additional_fields, custom_fields, )
        OpenAPI.validate_property(ResponseCustomerFindResult, Symbol("customers_count"), customers_count)
        OpenAPI.validate_property(ResponseCustomerFindResult, Symbol("customer"), customer)
        OpenAPI.validate_property(ResponseCustomerFindResult, Symbol("additional_fields"), additional_fields)
        OpenAPI.validate_property(ResponseCustomerFindResult, Symbol("custom_fields"), custom_fields)
        return new(customers_count, customer, additional_fields, custom_fields, )
    end
end # type ResponseCustomerFindResult

const _property_types_ResponseCustomerFindResult = Dict{Symbol,String}(Symbol("customers_count")=>"Int64", Symbol("customer")=>"Vector{Customer}", Symbol("additional_fields")=>"Any", Symbol("custom_fields")=>"Any", )
OpenAPI.property_type(::Type{ ResponseCustomerFindResult }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ResponseCustomerFindResult[name]))}

function check_required(o::ResponseCustomerFindResult)
    true
end

function OpenAPI.validate_property(::Type{ ResponseCustomerFindResult }, name::Symbol, val)




end
