# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""Response_Product_Brand_List_Result

    ResponseProductBrandListResult(;
        total_count=nothing,
        brands=nothing,
        additional_fields=nothing,
        custom_fields=nothing,
    )

    - total_count::Int64
    - brands::Vector{Brand}
    - additional_fields::Any
    - custom_fields::Any
"""
Base.@kwdef mutable struct ResponseProductBrandListResult <: OpenAPI.APIModel
    total_count::Union{Nothing, Int64} = nothing
    brands::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{Brand} }
    additional_fields::Union{Nothing, Any} = nothing
    custom_fields::Union{Nothing, Any} = nothing

    function ResponseProductBrandListResult(total_count, brands, additional_fields, custom_fields, )
        OpenAPI.validate_property(ResponseProductBrandListResult, Symbol("total_count"), total_count)
        OpenAPI.validate_property(ResponseProductBrandListResult, Symbol("brands"), brands)
        OpenAPI.validate_property(ResponseProductBrandListResult, Symbol("additional_fields"), additional_fields)
        OpenAPI.validate_property(ResponseProductBrandListResult, Symbol("custom_fields"), custom_fields)
        return new(total_count, brands, additional_fields, custom_fields, )
    end
end # type ResponseProductBrandListResult

const _property_types_ResponseProductBrandListResult = Dict{Symbol,String}(Symbol("total_count")=>"Int64", Symbol("brands")=>"Vector{Brand}", Symbol("additional_fields")=>"Any", Symbol("custom_fields")=>"Any", )
OpenAPI.property_type(::Type{ ResponseProductBrandListResult }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ResponseProductBrandListResult[name]))}

function check_required(o::ResponseProductBrandListResult)
    true
end

function OpenAPI.validate_property(::Type{ ResponseProductBrandListResult }, name::Symbol, val)




end
