# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""CategoryAddBatch

    CategoryAddBatch(;
        payload=nothing,
        idempotency_key=nothing,
    )

    - payload::Vector{CategoryAddBatchPayloadInner} : Contains an array of categories objects. The list of properties may vary depending on the specific platform.
    - idempotency_key::String : A unique identifier associated with a specific request. Repeated requests with the same &lt;strong&gt;idempotency_key&lt;/strong&gt; return a cached response without re-executing the business logic. &lt;strong&gt;Please note that the cache lifetime is 15 minutes.&lt;/strong&gt;
"""
Base.@kwdef mutable struct CategoryAddBatch <: OpenAPI.APIModel
    payload::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{CategoryAddBatchPayloadInner} }
    idempotency_key::Union{Nothing, String} = nothing

    function CategoryAddBatch(payload, idempotency_key, )
        OpenAPI.validate_property(CategoryAddBatch, Symbol("payload"), payload)
        OpenAPI.validate_property(CategoryAddBatch, Symbol("idempotency_key"), idempotency_key)
        return new(payload, idempotency_key, )
    end
end # type CategoryAddBatch

const _property_types_CategoryAddBatch = Dict{Symbol,String}(Symbol("payload")=>"Vector{CategoryAddBatchPayloadInner}", Symbol("idempotency_key")=>"String", )
OpenAPI.property_type(::Type{ CategoryAddBatch }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_CategoryAddBatch[name]))}

function check_required(o::CategoryAddBatch)
    o.payload === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ CategoryAddBatch }, name::Symbol, val)

    if name === Symbol("payload")
        OpenAPI.validate_param(name, "CategoryAddBatch", :maxItems, val, 250)
        OpenAPI.validate_param(name, "CategoryAddBatch", :minItems, val, 1)
    end

end
