# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""CartValidate_200_response_result

    CartValidate200ResponseResult(;
        status=nothing,
    )

    - status::String
"""
Base.@kwdef mutable struct CartValidate200ResponseResult <: OpenAPI.APIModel
    status::Union{Nothing, String} = nothing

    function CartValidate200ResponseResult(status, )
        OpenAPI.validate_property(CartValidate200ResponseResult, Symbol("status"), status)
        return new(status, )
    end
end # type CartValidate200ResponseResult

const _property_types_CartValidate200ResponseResult = Dict{Symbol,String}(Symbol("status")=>"String", )
OpenAPI.property_type(::Type{ CartValidate200ResponseResult }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_CartValidate200ResponseResult[name]))}

function check_required(o::CartValidate200ResponseResult)
    true
end

function OpenAPI.validate_property(::Type{ CartValidate200ResponseResult }, name::Symbol, val)

end
