# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""State

    State(;
        code=nothing,
        name=nothing,
        additional_fields=nothing,
        custom_fields=nothing,
    )

    - code::String
    - name::String
    - additional_fields::Any
    - custom_fields::Any
"""
Base.@kwdef mutable struct State <: OpenAPI.APIModel
    code::Union{Nothing, String} = nothing
    name::Union{Nothing, String} = nothing
    additional_fields::Union{Nothing, Any} = nothing
    custom_fields::Union{Nothing, Any} = nothing

    function State(code, name, additional_fields, custom_fields, )
        OpenAPI.validate_property(State, Symbol("code"), code)
        OpenAPI.validate_property(State, Symbol("name"), name)
        OpenAPI.validate_property(State, Symbol("additional_fields"), additional_fields)
        OpenAPI.validate_property(State, Symbol("custom_fields"), custom_fields)
        return new(code, name, additional_fields, custom_fields, )
    end
end # type State

const _property_types_State = Dict{Symbol,String}(Symbol("code")=>"String", Symbol("name")=>"String", Symbol("additional_fields")=>"Any", Symbol("custom_fields")=>"Any", )
OpenAPI.property_type(::Type{ State }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_State[name]))}

function check_required(o::State)
    true
end

function OpenAPI.validate_property(::Type{ State }, name::Symbol, val)




end
