# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""BasketLiveShippingServiceCreate_200_response_result

    BasketLiveShippingServiceCreate200ResponseResult(;
        id=nothing,
    )

    - id::Int64
"""
Base.@kwdef mutable struct BasketLiveShippingServiceCreate200ResponseResult <: OpenAPI.APIModel
    id::Union{Nothing, Int64} = nothing

    function BasketLiveShippingServiceCreate200ResponseResult(id, )
        OpenAPI.validate_property(BasketLiveShippingServiceCreate200ResponseResult, Symbol("id"), id)
        return new(id, )
    end
end # type BasketLiveShippingServiceCreate200ResponseResult

const _property_types_BasketLiveShippingServiceCreate200ResponseResult = Dict{Symbol,String}(Symbol("id")=>"Int64", )
OpenAPI.property_type(::Type{ BasketLiveShippingServiceCreate200ResponseResult }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_BasketLiveShippingServiceCreate200ResponseResult[name]))}

function check_required(o::BasketLiveShippingServiceCreate200ResponseResult)
    true
end

function OpenAPI.validate_property(::Type{ BasketLiveShippingServiceCreate200ResponseResult }, name::Symbol, val)

end
