# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""Response_Batch_Job_List_Result

    ResponseBatchJobListResult(;
        jobs=nothing,
        additional_fields=nothing,
        custom_fields=nothing,
    )

    - jobs::Vector{BatchJob}
    - additional_fields::Any
    - custom_fields::Any
"""
Base.@kwdef mutable struct ResponseBatchJobListResult <: OpenAPI.APIModel
    jobs::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{BatchJob} }
    additional_fields::Union{Nothing, Any} = nothing
    custom_fields::Union{Nothing, Any} = nothing

    function ResponseBatchJobListResult(jobs, additional_fields, custom_fields, )
        OpenAPI.validate_property(ResponseBatchJobListResult, Symbol("jobs"), jobs)
        OpenAPI.validate_property(ResponseBatchJobListResult, Symbol("additional_fields"), additional_fields)
        OpenAPI.validate_property(ResponseBatchJobListResult, Symbol("custom_fields"), custom_fields)
        return new(jobs, additional_fields, custom_fields, )
    end
end # type ResponseBatchJobListResult

const _property_types_ResponseBatchJobListResult = Dict{Symbol,String}(Symbol("jobs")=>"Vector{BatchJob}", Symbol("additional_fields")=>"Any", Symbol("custom_fields")=>"Any", )
OpenAPI.property_type(::Type{ ResponseBatchJobListResult }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ResponseBatchJobListResult[name]))}

function check_required(o::ResponseBatchJobListResult)
    true
end

function OpenAPI.validate_property(::Type{ ResponseBatchJobListResult }, name::Symbol, val)



end
