# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""Shipment_Item

    ShipmentItem(;
        order_product_id=nothing,
        product_id=nothing,
        variant_id=nothing,
        model=nothing,
        name=nothing,
        price=nothing,
        quantity=nothing,
        additional_fields=nothing,
        custom_fields=nothing,
    )

    - order_product_id::String
    - product_id::String
    - variant_id::String
    - model::String
    - name::String
    - price::Float64
    - quantity::Float64
    - additional_fields::Any
    - custom_fields::Any
"""
Base.@kwdef mutable struct ShipmentItem <: OpenAPI.APIModel
    order_product_id::Union{Nothing, String} = nothing
    product_id::Union{Nothing, String} = nothing
    variant_id::Union{Nothing, String} = nothing
    model::Union{Nothing, String} = nothing
    name::Union{Nothing, String} = nothing
    price::Union{Nothing, Float64} = nothing
    quantity::Union{Nothing, Float64} = nothing
    additional_fields::Union{Nothing, Any} = nothing
    custom_fields::Union{Nothing, Any} = nothing

    function ShipmentItem(order_product_id, product_id, variant_id, model, name, price, quantity, additional_fields, custom_fields, )
        OpenAPI.validate_property(ShipmentItem, Symbol("order_product_id"), order_product_id)
        OpenAPI.validate_property(ShipmentItem, Symbol("product_id"), product_id)
        OpenAPI.validate_property(ShipmentItem, Symbol("variant_id"), variant_id)
        OpenAPI.validate_property(ShipmentItem, Symbol("model"), model)
        OpenAPI.validate_property(ShipmentItem, Symbol("name"), name)
        OpenAPI.validate_property(ShipmentItem, Symbol("price"), price)
        OpenAPI.validate_property(ShipmentItem, Symbol("quantity"), quantity)
        OpenAPI.validate_property(ShipmentItem, Symbol("additional_fields"), additional_fields)
        OpenAPI.validate_property(ShipmentItem, Symbol("custom_fields"), custom_fields)
        return new(order_product_id, product_id, variant_id, model, name, price, quantity, additional_fields, custom_fields, )
    end
end # type ShipmentItem

const _property_types_ShipmentItem = Dict{Symbol,String}(Symbol("order_product_id")=>"String", Symbol("product_id")=>"String", Symbol("variant_id")=>"String", Symbol("model")=>"String", Symbol("name")=>"String", Symbol("price")=>"Float64", Symbol("quantity")=>"Float64", Symbol("additional_fields")=>"Any", Symbol("custom_fields")=>"Any", )
OpenAPI.property_type(::Type{ ShipmentItem }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ShipmentItem[name]))}

function check_required(o::ShipmentItem)
    true
end

function OpenAPI.validate_property(::Type{ ShipmentItem }, name::Symbol, val)









end
