# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""Response_Return_Reason_List_Result

    ResponseReturnReasonListResult(;
        return_reasons=nothing,
        additional_fields=nothing,
        custom_fields=nothing,
    )

    - return_reasons::Vector{Status}
    - additional_fields::Any
    - custom_fields::Any
"""
Base.@kwdef mutable struct ResponseReturnReasonListResult <: OpenAPI.APIModel
    return_reasons::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{Status} }
    additional_fields::Union{Nothing, Any} = nothing
    custom_fields::Union{Nothing, Any} = nothing

    function ResponseReturnReasonListResult(return_reasons, additional_fields, custom_fields, )
        OpenAPI.validate_property(ResponseReturnReasonListResult, Symbol("return_reasons"), return_reasons)
        OpenAPI.validate_property(ResponseReturnReasonListResult, Symbol("additional_fields"), additional_fields)
        OpenAPI.validate_property(ResponseReturnReasonListResult, Symbol("custom_fields"), custom_fields)
        return new(return_reasons, additional_fields, custom_fields, )
    end
end # type ResponseReturnReasonListResult

const _property_types_ResponseReturnReasonListResult = Dict{Symbol,String}(Symbol("return_reasons")=>"Vector{Status}", Symbol("additional_fields")=>"Any", Symbol("custom_fields")=>"Any", )
OpenAPI.property_type(::Type{ ResponseReturnReasonListResult }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ResponseReturnReasonListResult[name]))}

function check_required(o::ResponseReturnReasonListResult)
    true
end

function OpenAPI.validate_property(::Type{ ResponseReturnReasonListResult }, name::Symbol, val)



end
