# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""Model_Response_Cart_Methods

    ModelResponseCartMethods(;
        return_code=nothing,
        return_message=nothing,
        result=nothing,
        additional_fields=nothing,
        custom_fields=nothing,
    )

    - return_code::Int64
    - return_message::String
    - result::ResponseCartMethodsResult
    - additional_fields::Any
    - custom_fields::Any
"""
Base.@kwdef mutable struct ModelResponseCartMethods <: OpenAPI.APIModel
    return_code::Union{Nothing, Int64} = nothing
    return_message::Union{Nothing, String} = nothing
    result = nothing # spec type: Union{ Nothing, ResponseCartMethodsResult }
    additional_fields::Union{Nothing, Any} = nothing
    custom_fields::Union{Nothing, Any} = nothing

    function ModelResponseCartMethods(return_code, return_message, result, additional_fields, custom_fields, )
        OpenAPI.validate_property(ModelResponseCartMethods, Symbol("return_code"), return_code)
        OpenAPI.validate_property(ModelResponseCartMethods, Symbol("return_message"), return_message)
        OpenAPI.validate_property(ModelResponseCartMethods, Symbol("result"), result)
        OpenAPI.validate_property(ModelResponseCartMethods, Symbol("additional_fields"), additional_fields)
        OpenAPI.validate_property(ModelResponseCartMethods, Symbol("custom_fields"), custom_fields)
        return new(return_code, return_message, result, additional_fields, custom_fields, )
    end
end # type ModelResponseCartMethods

const _property_types_ModelResponseCartMethods = Dict{Symbol,String}(Symbol("return_code")=>"Int64", Symbol("return_message")=>"String", Symbol("result")=>"ResponseCartMethodsResult", Symbol("additional_fields")=>"Any", Symbol("custom_fields")=>"Any", )
OpenAPI.property_type(::Type{ ModelResponseCartMethods }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ModelResponseCartMethods[name]))}

function check_required(o::ModelResponseCartMethods)
    true
end

function OpenAPI.validate_property(::Type{ ModelResponseCartMethods }, name::Symbol, val)





end
