# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""OrderCount_200_response_result

    OrderCount200ResponseResult(;
        orders_count=nothing,
    )

    - orders_count::Int64
"""
Base.@kwdef mutable struct OrderCount200ResponseResult <: OpenAPI.APIModel
    orders_count::Union{Nothing, Int64} = nothing

    function OrderCount200ResponseResult(orders_count, )
        OpenAPI.validate_property(OrderCount200ResponseResult, Symbol("orders_count"), orders_count)
        return new(orders_count, )
    end
end # type OrderCount200ResponseResult

const _property_types_OrderCount200ResponseResult = Dict{Symbol,String}(Symbol("orders_count")=>"Int64", )
OpenAPI.property_type(::Type{ OrderCount200ResponseResult }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_OrderCount200ResponseResult[name]))}

function check_required(o::OrderCount200ResponseResult)
    true
end

function OpenAPI.validate_property(::Type{ OrderCount200ResponseResult }, name::Symbol, val)

end
