# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""Analytics_Product

    AnalyticsProduct(;
        product_id=nothing,
        variant_id=nothing,
        sku=nothing,
        name=nothing,
        category_ids=nothing,
        metrics=nothing,
        additional_fields=nothing,
        custom_fields=nothing,
    )

    - product_id::String
    - variant_id::String
    - sku::String
    - name::String
    - category_ids::Vector{String}
    - metrics::AnalyticsProductMetric
    - additional_fields::Any
    - custom_fields::Any
"""
Base.@kwdef mutable struct AnalyticsProduct <: OpenAPI.APIModel
    product_id::Union{Nothing, String} = nothing
    variant_id::Union{Nothing, String} = nothing
    sku::Union{Nothing, String} = nothing
    name::Union{Nothing, String} = nothing
    category_ids::Union{Nothing, Vector{String}} = nothing
    metrics = nothing # spec type: Union{ Nothing, AnalyticsProductMetric }
    additional_fields::Union{Nothing, Any} = nothing
    custom_fields::Union{Nothing, Any} = nothing

    function AnalyticsProduct(product_id, variant_id, sku, name, category_ids, metrics, additional_fields, custom_fields, )
        OpenAPI.validate_property(AnalyticsProduct, Symbol("product_id"), product_id)
        OpenAPI.validate_property(AnalyticsProduct, Symbol("variant_id"), variant_id)
        OpenAPI.validate_property(AnalyticsProduct, Symbol("sku"), sku)
        OpenAPI.validate_property(AnalyticsProduct, Symbol("name"), name)
        OpenAPI.validate_property(AnalyticsProduct, Symbol("category_ids"), category_ids)
        OpenAPI.validate_property(AnalyticsProduct, Symbol("metrics"), metrics)
        OpenAPI.validate_property(AnalyticsProduct, Symbol("additional_fields"), additional_fields)
        OpenAPI.validate_property(AnalyticsProduct, Symbol("custom_fields"), custom_fields)
        return new(product_id, variant_id, sku, name, category_ids, metrics, additional_fields, custom_fields, )
    end
end # type AnalyticsProduct

const _property_types_AnalyticsProduct = Dict{Symbol,String}(Symbol("product_id")=>"String", Symbol("variant_id")=>"String", Symbol("sku")=>"String", Symbol("name")=>"String", Symbol("category_ids")=>"Vector{String}", Symbol("metrics")=>"AnalyticsProductMetric", Symbol("additional_fields")=>"Any", Symbol("custom_fields")=>"Any", )
OpenAPI.property_type(::Type{ AnalyticsProduct }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_AnalyticsProduct[name]))}

function check_required(o::AnalyticsProduct)
    true
end

function OpenAPI.validate_property(::Type{ AnalyticsProduct }, name::Symbol, val)








end
