# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""Response_Subscriber_List_Result

    ResponseSubscriberListResult(;
        total_count=nothing,
        subscribers=nothing,
        additional_fields=nothing,
        custom_fields=nothing,
    )

    - total_count::Int64
    - subscribers::Vector{Subscriber}
    - additional_fields::Any
    - custom_fields::Any
"""
Base.@kwdef mutable struct ResponseSubscriberListResult <: OpenAPI.APIModel
    total_count::Union{Nothing, Int64} = nothing
    subscribers::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{Subscriber} }
    additional_fields::Union{Nothing, Any} = nothing
    custom_fields::Union{Nothing, Any} = nothing

    function ResponseSubscriberListResult(total_count, subscribers, additional_fields, custom_fields, )
        OpenAPI.validate_property(ResponseSubscriberListResult, Symbol("total_count"), total_count)
        OpenAPI.validate_property(ResponseSubscriberListResult, Symbol("subscribers"), subscribers)
        OpenAPI.validate_property(ResponseSubscriberListResult, Symbol("additional_fields"), additional_fields)
        OpenAPI.validate_property(ResponseSubscriberListResult, Symbol("custom_fields"), custom_fields)
        return new(total_count, subscribers, additional_fields, custom_fields, )
    end
end # type ResponseSubscriberListResult

const _property_types_ResponseSubscriberListResult = Dict{Symbol,String}(Symbol("total_count")=>"Int64", Symbol("subscribers")=>"Vector{Subscriber}", Symbol("additional_fields")=>"Any", Symbol("custom_fields")=>"Any", )
OpenAPI.property_type(::Type{ ResponseSubscriberListResult }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ResponseSubscriberListResult[name]))}

function check_required(o::ResponseSubscriberListResult)
    true
end

function OpenAPI.validate_property(::Type{ ResponseSubscriberListResult }, name::Symbol, val)




end
