# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""OrderAdd_note_attributes_inner

    OrderAddNoteAttributesInner(;
        name=nothing,
        value=nothing,
    )

    - name::String
    - value::String
"""
Base.@kwdef mutable struct OrderAddNoteAttributesInner <: OpenAPI.APIModel
    name::Union{Nothing, String} = nothing
    value::Union{Nothing, String} = nothing

    function OrderAddNoteAttributesInner(name, value, )
        OpenAPI.validate_property(OrderAddNoteAttributesInner, Symbol("name"), name)
        OpenAPI.validate_property(OrderAddNoteAttributesInner, Symbol("value"), value)
        return new(name, value, )
    end
end # type OrderAddNoteAttributesInner

const _property_types_OrderAddNoteAttributesInner = Dict{Symbol,String}(Symbol("name")=>"String", Symbol("value")=>"String", )
OpenAPI.property_type(::Type{ OrderAddNoteAttributesInner }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_OrderAddNoteAttributesInner[name]))}

function check_required(o::OrderAddNoteAttributesInner)
    true
end

function OpenAPI.validate_property(::Type{ OrderAddNoteAttributesInner }, name::Symbol, val)


end
