# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ProductFind_200_response_result

    ProductFind200ResponseResult(;
        product=nothing,
    )

    - product::Vector{ProductFind200ResponseResultProductInner}
"""
Base.@kwdef mutable struct ProductFind200ResponseResult <: OpenAPI.APIModel
    product::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{ProductFind200ResponseResultProductInner} }

    function ProductFind200ResponseResult(product, )
        OpenAPI.validate_property(ProductFind200ResponseResult, Symbol("product"), product)
        return new(product, )
    end
end # type ProductFind200ResponseResult

const _property_types_ProductFind200ResponseResult = Dict{Symbol,String}(Symbol("product")=>"Vector{ProductFind200ResponseResultProductInner}", )
OpenAPI.property_type(::Type{ ProductFind200ResponseResult }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ProductFind200ResponseResult[name]))}

function check_required(o::ProductFind200ResponseResult)
    true
end

function OpenAPI.validate_property(::Type{ ProductFind200ResponseResult }, name::Symbol, val)

end
