# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ParamDefinition_FilteringConditions_FilterGroup

    ParamDefinitionFilteringConditionsFilterGroup(;
        and=nothing,
        or=nothing,
        not=nothing,
    )

    - and::Vector{Any}
    - or::Vector{Any}
    - not::Any
"""
Base.@kwdef mutable struct ParamDefinitionFilteringConditionsFilterGroup <: OpenAPI.APIModel
    and::Union{Nothing, Vector{Any}} = nothing
    or::Union{Nothing, Vector{Any}} = nothing
    not::Union{Nothing, Any} = nothing

    function ParamDefinitionFilteringConditionsFilterGroup(and, or, not, )
        OpenAPI.validate_property(ParamDefinitionFilteringConditionsFilterGroup, Symbol("and"), and)
        OpenAPI.validate_property(ParamDefinitionFilteringConditionsFilterGroup, Symbol("or"), or)
        OpenAPI.validate_property(ParamDefinitionFilteringConditionsFilterGroup, Symbol("not"), not)
        return new(and, or, not, )
    end
end # type ParamDefinitionFilteringConditionsFilterGroup

const _property_types_ParamDefinitionFilteringConditionsFilterGroup = Dict{Symbol,String}(Symbol("and")=>"Vector{Any}", Symbol("or")=>"Vector{Any}", Symbol("not")=>"Any", )
OpenAPI.property_type(::Type{ ParamDefinitionFilteringConditionsFilterGroup }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ParamDefinitionFilteringConditionsFilterGroup[name]))}

function check_required(o::ParamDefinitionFilteringConditionsFilterGroup)
    true
end

function OpenAPI.validate_property(::Type{ ParamDefinitionFilteringConditionsFilterGroup }, name::Symbol, val)



end
