# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""Order_Calculate_ShippingRate

    OrderCalculateShippingRate(;
        code=nothing,
        name=nothing,
        price=nothing,
        price_inc_tax=nothing,
        tax=nothing,
        tax_rate=nothing,
        additional_fields=nothing,
        custom_fields=nothing,
    )

    - code::String
    - name::String
    - price::Float64
    - price_inc_tax::Float64
    - tax::Float64
    - tax_rate::Float64
    - additional_fields::Any
    - custom_fields::Any
"""
Base.@kwdef mutable struct OrderCalculateShippingRate <: OpenAPI.APIModel
    code::Union{Nothing, String} = nothing
    name::Union{Nothing, String} = nothing
    price::Union{Nothing, Float64} = nothing
    price_inc_tax::Union{Nothing, Float64} = nothing
    tax::Union{Nothing, Float64} = nothing
    tax_rate::Union{Nothing, Float64} = nothing
    additional_fields::Union{Nothing, Any} = nothing
    custom_fields::Union{Nothing, Any} = nothing

    function OrderCalculateShippingRate(code, name, price, price_inc_tax, tax, tax_rate, additional_fields, custom_fields, )
        OpenAPI.validate_property(OrderCalculateShippingRate, Symbol("code"), code)
        OpenAPI.validate_property(OrderCalculateShippingRate, Symbol("name"), name)
        OpenAPI.validate_property(OrderCalculateShippingRate, Symbol("price"), price)
        OpenAPI.validate_property(OrderCalculateShippingRate, Symbol("price_inc_tax"), price_inc_tax)
        OpenAPI.validate_property(OrderCalculateShippingRate, Symbol("tax"), tax)
        OpenAPI.validate_property(OrderCalculateShippingRate, Symbol("tax_rate"), tax_rate)
        OpenAPI.validate_property(OrderCalculateShippingRate, Symbol("additional_fields"), additional_fields)
        OpenAPI.validate_property(OrderCalculateShippingRate, Symbol("custom_fields"), custom_fields)
        return new(code, name, price, price_inc_tax, tax, tax_rate, additional_fields, custom_fields, )
    end
end # type OrderCalculateShippingRate

const _property_types_OrderCalculateShippingRate = Dict{Symbol,String}(Symbol("code")=>"String", Symbol("name")=>"String", Symbol("price")=>"Float64", Symbol("price_inc_tax")=>"Float64", Symbol("tax")=>"Float64", Symbol("tax_rate")=>"Float64", Symbol("additional_fields")=>"Any", Symbol("custom_fields")=>"Any", )
OpenAPI.property_type(::Type{ OrderCalculateShippingRate }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_OrderCalculateShippingRate[name]))}

function check_required(o::OrderCalculateShippingRate)
    true
end

function OpenAPI.validate_property(::Type{ OrderCalculateShippingRate }, name::Symbol, val)








end
