# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""WebhookEvents_200_response_result_events_inner

    WebhookEvents200ResponseResultEventsInner(;
        webhook_name=nothing,
        entity=nothing,
        action=nothing,
    )

    - webhook_name::String
    - entity::String
    - action::String
"""
Base.@kwdef mutable struct WebhookEvents200ResponseResultEventsInner <: OpenAPI.APIModel
    webhook_name::Union{Nothing, String} = nothing
    entity::Union{Nothing, String} = nothing
    action::Union{Nothing, String} = nothing

    function WebhookEvents200ResponseResultEventsInner(webhook_name, entity, action, )
        OpenAPI.validate_property(WebhookEvents200ResponseResultEventsInner, Symbol("webhook_name"), webhook_name)
        OpenAPI.validate_property(WebhookEvents200ResponseResultEventsInner, Symbol("entity"), entity)
        OpenAPI.validate_property(WebhookEvents200ResponseResultEventsInner, Symbol("action"), action)
        return new(webhook_name, entity, action, )
    end
end # type WebhookEvents200ResponseResultEventsInner

const _property_types_WebhookEvents200ResponseResultEventsInner = Dict{Symbol,String}(Symbol("webhook_name")=>"String", Symbol("entity")=>"String", Symbol("action")=>"String", )
OpenAPI.property_type(::Type{ WebhookEvents200ResponseResultEventsInner }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_WebhookEvents200ResponseResultEventsInner[name]))}

function check_required(o::WebhookEvents200ResponseResultEventsInner)
    true
end

function OpenAPI.validate_property(::Type{ WebhookEvents200ResponseResultEventsInner }, name::Symbol, val)



end
