# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""Response_Attribute_Attributeset_List_Result

    ResponseAttributeAttributesetListResult(;
        attribute_set=nothing,
        additional_fields=nothing,
        custom_fields=nothing,
    )

    - attribute_set::Vector{StoreAttributeAttributeSet}
    - additional_fields::Any
    - custom_fields::Any
"""
Base.@kwdef mutable struct ResponseAttributeAttributesetListResult <: OpenAPI.APIModel
    attribute_set::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{StoreAttributeAttributeSet} }
    additional_fields::Union{Nothing, Any} = nothing
    custom_fields::Union{Nothing, Any} = nothing

    function ResponseAttributeAttributesetListResult(attribute_set, additional_fields, custom_fields, )
        OpenAPI.validate_property(ResponseAttributeAttributesetListResult, Symbol("attribute_set"), attribute_set)
        OpenAPI.validate_property(ResponseAttributeAttributesetListResult, Symbol("additional_fields"), additional_fields)
        OpenAPI.validate_property(ResponseAttributeAttributesetListResult, Symbol("custom_fields"), custom_fields)
        return new(attribute_set, additional_fields, custom_fields, )
    end
end # type ResponseAttributeAttributesetListResult

const _property_types_ResponseAttributeAttributesetListResult = Dict{Symbol,String}(Symbol("attribute_set")=>"Vector{StoreAttributeAttributeSet}", Symbol("additional_fields")=>"Any", Symbol("custom_fields")=>"Any", )
OpenAPI.property_type(::Type{ ResponseAttributeAttributesetListResult }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ResponseAttributeAttributesetListResult[name]))}

function check_required(o::ResponseAttributeAttributesetListResult)
    true
end

function OpenAPI.validate_property(::Type{ ResponseAttributeAttributesetListResult }, name::Symbol, val)



end
