# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""AttributeDelete_200_response_result

    AttributeDelete200ResponseResult(;
        deleted=nothing,
    )

    - deleted::String
"""
Base.@kwdef mutable struct AttributeDelete200ResponseResult <: OpenAPI.APIModel
    deleted::Union{Nothing, String} = nothing

    function AttributeDelete200ResponseResult(deleted, )
        OpenAPI.validate_property(AttributeDelete200ResponseResult, Symbol("deleted"), deleted)
        return new(deleted, )
    end
end # type AttributeDelete200ResponseResult

const _property_types_AttributeDelete200ResponseResult = Dict{Symbol,String}(Symbol("deleted")=>"String", )
OpenAPI.property_type(::Type{ AttributeDelete200ResponseResult }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_AttributeDelete200ResponseResult[name]))}

function check_required(o::AttributeDelete200ResponseResult)
    true
end

function OpenAPI.validate_property(::Type{ AttributeDelete200ResponseResult }, name::Symbol, val)

end
