# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""Order_Calculate_Discount

    OrderCalculateDiscount(;
        code=nothing,
        value=nothing,
        type=nothing,
        free_shipping=nothing,
        additional_fields=nothing,
        custom_fields=nothing,
    )

    - code::String
    - value::Float64
    - type::String
    - free_shipping::Bool
    - additional_fields::Any
    - custom_fields::Any
"""
Base.@kwdef mutable struct OrderCalculateDiscount <: OpenAPI.APIModel
    code::Union{Nothing, String} = nothing
    value::Union{Nothing, Float64} = nothing
    type::Union{Nothing, String} = nothing
    free_shipping::Union{Nothing, Bool} = nothing
    additional_fields::Union{Nothing, Any} = nothing
    custom_fields::Union{Nothing, Any} = nothing

    function OrderCalculateDiscount(code, value, type, free_shipping, additional_fields, custom_fields, )
        OpenAPI.validate_property(OrderCalculateDiscount, Symbol("code"), code)
        OpenAPI.validate_property(OrderCalculateDiscount, Symbol("value"), value)
        OpenAPI.validate_property(OrderCalculateDiscount, Symbol("type"), type)
        OpenAPI.validate_property(OrderCalculateDiscount, Symbol("free_shipping"), free_shipping)
        OpenAPI.validate_property(OrderCalculateDiscount, Symbol("additional_fields"), additional_fields)
        OpenAPI.validate_property(OrderCalculateDiscount, Symbol("custom_fields"), custom_fields)
        return new(code, value, type, free_shipping, additional_fields, custom_fields, )
    end
end # type OrderCalculateDiscount

const _property_types_OrderCalculateDiscount = Dict{Symbol,String}(Symbol("code")=>"String", Symbol("value")=>"Float64", Symbol("type")=>"String", Symbol("free_shipping")=>"Bool", Symbol("additional_fields")=>"Any", Symbol("custom_fields")=>"Any", )
OpenAPI.property_type(::Type{ OrderCalculateDiscount }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_OrderCalculateDiscount[name]))}

function check_required(o::OrderCalculateDiscount)
    true
end

function OpenAPI.validate_property(::Type{ OrderCalculateDiscount }, name::Symbol, val)






end
