# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""Product_Option_Item

    ProductOptionItem(;
        id=nothing,
        product_option_item_id=nothing,
        name=nothing,
        sort_order=nothing,
        price=nothing,
        weight=nothing,
        quantity=nothing,
        type_price=nothing,
        sku=nothing,
        is_default=nothing,
        additional_fields=nothing,
        custom_fields=nothing,
    )

    - id::String
    - product_option_item_id::String
    - name::String
    - sort_order::Int64
    - price::String
    - weight::String
    - quantity::Int64
    - type_price::String
    - sku::String
    - is_default::Bool
    - additional_fields::Any
    - custom_fields::Any
"""
Base.@kwdef mutable struct ProductOptionItem <: OpenAPI.APIModel
    id::Union{Nothing, String} = nothing
    product_option_item_id::Union{Nothing, String} = nothing
    name::Union{Nothing, String} = nothing
    sort_order::Union{Nothing, Int64} = nothing
    price::Union{Nothing, String} = nothing
    weight::Union{Nothing, String} = nothing
    quantity::Union{Nothing, Int64} = nothing
    type_price::Union{Nothing, String} = nothing
    sku::Union{Nothing, String} = nothing
    is_default::Union{Nothing, Bool} = nothing
    additional_fields::Union{Nothing, Any} = nothing
    custom_fields::Union{Nothing, Any} = nothing

    function ProductOptionItem(id, product_option_item_id, name, sort_order, price, weight, quantity, type_price, sku, is_default, additional_fields, custom_fields, )
        OpenAPI.validate_property(ProductOptionItem, Symbol("id"), id)
        OpenAPI.validate_property(ProductOptionItem, Symbol("product_option_item_id"), product_option_item_id)
        OpenAPI.validate_property(ProductOptionItem, Symbol("name"), name)
        OpenAPI.validate_property(ProductOptionItem, Symbol("sort_order"), sort_order)
        OpenAPI.validate_property(ProductOptionItem, Symbol("price"), price)
        OpenAPI.validate_property(ProductOptionItem, Symbol("weight"), weight)
        OpenAPI.validate_property(ProductOptionItem, Symbol("quantity"), quantity)
        OpenAPI.validate_property(ProductOptionItem, Symbol("type_price"), type_price)
        OpenAPI.validate_property(ProductOptionItem, Symbol("sku"), sku)
        OpenAPI.validate_property(ProductOptionItem, Symbol("is_default"), is_default)
        OpenAPI.validate_property(ProductOptionItem, Symbol("additional_fields"), additional_fields)
        OpenAPI.validate_property(ProductOptionItem, Symbol("custom_fields"), custom_fields)
        return new(id, product_option_item_id, name, sort_order, price, weight, quantity, type_price, sku, is_default, additional_fields, custom_fields, )
    end
end # type ProductOptionItem

const _property_types_ProductOptionItem = Dict{Symbol,String}(Symbol("id")=>"String", Symbol("product_option_item_id")=>"String", Symbol("name")=>"String", Symbol("sort_order")=>"Int64", Symbol("price")=>"String", Symbol("weight")=>"String", Symbol("quantity")=>"Int64", Symbol("type_price")=>"String", Symbol("sku")=>"String", Symbol("is_default")=>"Bool", Symbol("additional_fields")=>"Any", Symbol("custom_fields")=>"Any", )
OpenAPI.property_type(::Type{ ProductOptionItem }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ProductOptionItem[name]))}

function check_required(o::ProductOptionItem)
    true
end

function OpenAPI.validate_property(::Type{ ProductOptionItem }, name::Symbol, val)












end
