# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""Order_Totals

    OrderTotals(;
        total=nothing,
        subtotal=nothing,
        shipping=nothing,
        tax=nothing,
        discount=nothing,
        additional_fields=nothing,
        custom_fields=nothing,
    )

    - total::Float64
    - subtotal::Float64
    - shipping::Float64
    - tax::Float64
    - discount::Float64
    - additional_fields::Any
    - custom_fields::Any
"""
Base.@kwdef mutable struct OrderTotals <: OpenAPI.APIModel
    total::Union{Nothing, Float64} = nothing
    subtotal::Union{Nothing, Float64} = nothing
    shipping::Union{Nothing, Float64} = nothing
    tax::Union{Nothing, Float64} = nothing
    discount::Union{Nothing, Float64} = nothing
    additional_fields::Union{Nothing, Any} = nothing
    custom_fields::Union{Nothing, Any} = nothing

    function OrderTotals(total, subtotal, shipping, tax, discount, additional_fields, custom_fields, )
        OpenAPI.validate_property(OrderTotals, Symbol("total"), total)
        OpenAPI.validate_property(OrderTotals, Symbol("subtotal"), subtotal)
        OpenAPI.validate_property(OrderTotals, Symbol("shipping"), shipping)
        OpenAPI.validate_property(OrderTotals, Symbol("tax"), tax)
        OpenAPI.validate_property(OrderTotals, Symbol("discount"), discount)
        OpenAPI.validate_property(OrderTotals, Symbol("additional_fields"), additional_fields)
        OpenAPI.validate_property(OrderTotals, Symbol("custom_fields"), custom_fields)
        return new(total, subtotal, shipping, tax, discount, additional_fields, custom_fields, )
    end
end # type OrderTotals

const _property_types_OrderTotals = Dict{Symbol,String}(Symbol("total")=>"Float64", Symbol("subtotal")=>"Float64", Symbol("shipping")=>"Float64", Symbol("tax")=>"Float64", Symbol("discount")=>"Float64", Symbol("additional_fields")=>"Any", Symbol("custom_fields")=>"Any", )
OpenAPI.property_type(::Type{ OrderTotals }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_OrderTotals[name]))}

function check_required(o::OrderTotals)
    true
end

function OpenAPI.validate_property(::Type{ OrderTotals }, name::Symbol, val)







end
