# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""OrderFind_200_response_result

    OrderFind200ResponseResult(;
        order=nothing,
    )

    - order::Vector{Order}
"""
Base.@kwdef mutable struct OrderFind200ResponseResult <: OpenAPI.APIModel
    order::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{Order} }

    function OrderFind200ResponseResult(order, )
        OpenAPI.validate_property(OrderFind200ResponseResult, Symbol("order"), order)
        return new(order, )
    end
end # type OrderFind200ResponseResult

const _property_types_OrderFind200ResponseResult = Dict{Symbol,String}(Symbol("order")=>"Vector{Order}", )
OpenAPI.property_type(::Type{ OrderFind200ResponseResult }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_OrderFind200ResponseResult[name]))}

function check_required(o::OrderFind200ResponseResult)
    true
end

function OpenAPI.validate_property(::Type{ OrderFind200ResponseResult }, name::Symbol, val)

end
