# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""OrderShipmentAdd_200_response_result

    OrderShipmentAdd200ResponseResult(;
        shipment_id=nothing,
    )

    - shipment_id::String
"""
Base.@kwdef mutable struct OrderShipmentAdd200ResponseResult <: OpenAPI.APIModel
    shipment_id::Union{Nothing, String} = nothing

    function OrderShipmentAdd200ResponseResult(shipment_id, )
        OpenAPI.validate_property(OrderShipmentAdd200ResponseResult, Symbol("shipment_id"), shipment_id)
        return new(shipment_id, )
    end
end # type OrderShipmentAdd200ResponseResult

const _property_types_OrderShipmentAdd200ResponseResult = Dict{Symbol,String}(Symbol("shipment_id")=>"String", )
OpenAPI.property_type(::Type{ OrderShipmentAdd200ResponseResult }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_OrderShipmentAdd200ResponseResult[name]))}

function check_required(o::OrderShipmentAdd200ResponseResult)
    true
end

function OpenAPI.validate_property(::Type{ OrderShipmentAdd200ResponseResult }, name::Symbol, val)

end
