# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""AccountCartList_200_response_result_carts_inner

    AccountCartList200ResponseResultCartsInner(;
        id=nothing,
        url=nothing,
        store_key=nothing,
        cart_id=nothing,
        total_calls=nothing,
    )

    - id::String
    - url::String
    - store_key::String
    - cart_id::String
    - total_calls::String
"""
Base.@kwdef mutable struct AccountCartList200ResponseResultCartsInner <: OpenAPI.APIModel
    id::Union{Nothing, String} = nothing
    url::Union{Nothing, String} = nothing
    store_key::Union{Nothing, String} = nothing
    cart_id::Union{Nothing, String} = nothing
    total_calls::Union{Nothing, String} = nothing

    function AccountCartList200ResponseResultCartsInner(id, url, store_key, cart_id, total_calls, )
        OpenAPI.validate_property(AccountCartList200ResponseResultCartsInner, Symbol("id"), id)
        OpenAPI.validate_property(AccountCartList200ResponseResultCartsInner, Symbol("url"), url)
        OpenAPI.validate_property(AccountCartList200ResponseResultCartsInner, Symbol("store_key"), store_key)
        OpenAPI.validate_property(AccountCartList200ResponseResultCartsInner, Symbol("cart_id"), cart_id)
        OpenAPI.validate_property(AccountCartList200ResponseResultCartsInner, Symbol("total_calls"), total_calls)
        return new(id, url, store_key, cart_id, total_calls, )
    end
end # type AccountCartList200ResponseResultCartsInner

const _property_types_AccountCartList200ResponseResultCartsInner = Dict{Symbol,String}(Symbol("id")=>"String", Symbol("url")=>"String", Symbol("store_key")=>"String", Symbol("cart_id")=>"String", Symbol("total_calls")=>"String", )
OpenAPI.property_type(::Type{ AccountCartList200ResponseResultCartsInner }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_AccountCartList200ResponseResultCartsInner[name]))}

function check_required(o::AccountCartList200ResponseResultCartsInner)
    true
end

function OpenAPI.validate_property(::Type{ AccountCartList200ResponseResultCartsInner }, name::Symbol, val)





end
