# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""Response_Product_Currency_List_Result

    ResponseProductCurrencyListResult(;
        total_count=nothing,
        currency=nothing,
        additional_fields=nothing,
        custom_fields=nothing,
    )

    - total_count::Int64
    - currency::Vector{Currency}
    - additional_fields::Any
    - custom_fields::Any
"""
Base.@kwdef mutable struct ResponseProductCurrencyListResult <: OpenAPI.APIModel
    total_count::Union{Nothing, Int64} = nothing
    currency::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{Currency} }
    additional_fields::Union{Nothing, Any} = nothing
    custom_fields::Union{Nothing, Any} = nothing

    function ResponseProductCurrencyListResult(total_count, currency, additional_fields, custom_fields, )
        OpenAPI.validate_property(ResponseProductCurrencyListResult, Symbol("total_count"), total_count)
        OpenAPI.validate_property(ResponseProductCurrencyListResult, Symbol("currency"), currency)
        OpenAPI.validate_property(ResponseProductCurrencyListResult, Symbol("additional_fields"), additional_fields)
        OpenAPI.validate_property(ResponseProductCurrencyListResult, Symbol("custom_fields"), custom_fields)
        return new(total_count, currency, additional_fields, custom_fields, )
    end
end # type ResponseProductCurrencyListResult

const _property_types_ResponseProductCurrencyListResult = Dict{Symbol,String}(Symbol("total_count")=>"Int64", Symbol("currency")=>"Vector{Currency}", Symbol("additional_fields")=>"Any", Symbol("custom_fields")=>"Any", )
OpenAPI.property_type(::Type{ ResponseProductCurrencyListResult }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ResponseProductCurrencyListResult[name]))}

function check_required(o::ResponseProductCurrencyListResult)
    true
end

function OpenAPI.validate_property(::Type{ ResponseProductCurrencyListResult }, name::Symbol, val)




end
