# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""Status

    Status(;
        id=nothing,
        name=nothing,
        additional_fields=nothing,
        custom_fields=nothing,
    )

    - id::String
    - name::String
    - additional_fields::Any
    - custom_fields::Any
"""
Base.@kwdef mutable struct Status <: OpenAPI.APIModel
    id::Union{Nothing, String} = nothing
    name::Union{Nothing, String} = nothing
    additional_fields::Union{Nothing, Any} = nothing
    custom_fields::Union{Nothing, Any} = nothing

    function Status(id, name, additional_fields, custom_fields, )
        OpenAPI.validate_property(Status, Symbol("id"), id)
        OpenAPI.validate_property(Status, Symbol("name"), name)
        OpenAPI.validate_property(Status, Symbol("additional_fields"), additional_fields)
        OpenAPI.validate_property(Status, Symbol("custom_fields"), custom_fields)
        return new(id, name, additional_fields, custom_fields, )
    end
end # type Status

const _property_types_Status = Dict{Symbol,String}(Symbol("id")=>"String", Symbol("name")=>"String", Symbol("additional_fields")=>"Any", Symbol("custom_fields")=>"Any", )
OpenAPI.property_type(::Type{ Status }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_Status[name]))}

function check_required(o::Status)
    true
end

function OpenAPI.validate_property(::Type{ Status }, name::Symbol, val)




end
