# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""Analytics_Period

    AnalyticsPeriod(;
        date_from=nothing,
        date_to=nothing,
        additional_fields=nothing,
        custom_fields=nothing,
    )

    - date_from::String
    - date_to::String
    - additional_fields::Any
    - custom_fields::Any
"""
Base.@kwdef mutable struct AnalyticsPeriod <: OpenAPI.APIModel
    date_from::Union{Nothing, String} = nothing
    date_to::Union{Nothing, String} = nothing
    additional_fields::Union{Nothing, Any} = nothing
    custom_fields::Union{Nothing, Any} = nothing

    function AnalyticsPeriod(date_from, date_to, additional_fields, custom_fields, )
        OpenAPI.validate_property(AnalyticsPeriod, Symbol("date_from"), date_from)
        OpenAPI.validate_property(AnalyticsPeriod, Symbol("date_to"), date_to)
        OpenAPI.validate_property(AnalyticsPeriod, Symbol("additional_fields"), additional_fields)
        OpenAPI.validate_property(AnalyticsPeriod, Symbol("custom_fields"), custom_fields)
        return new(date_from, date_to, additional_fields, custom_fields, )
    end
end # type AnalyticsPeriod

const _property_types_AnalyticsPeriod = Dict{Symbol,String}(Symbol("date_from")=>"String", Symbol("date_to")=>"String", Symbol("additional_fields")=>"Any", Symbol("custom_fields")=>"Any", )
OpenAPI.property_type(::Type{ AnalyticsPeriod }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_AnalyticsPeriod[name]))}

function check_required(o::AnalyticsPeriod)
    true
end

function OpenAPI.validate_property(::Type{ AnalyticsPeriod }, name::Symbol, val)




end
