# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ProductAdd_size_chart
A size chart for the product. Only one property is supported.

    ProductAddSizeChart(;
        id=nothing,
        url=nothing,
    )

    - id::String : Defines a pre-generated size chart template
    - url::String : Defines a size chart image URL
"""
Base.@kwdef mutable struct ProductAddSizeChart <: OpenAPI.APIModel
    id::Union{Nothing, String} = nothing
    url::Union{Nothing, String} = nothing

    function ProductAddSizeChart(id, url, )
        OpenAPI.validate_property(ProductAddSizeChart, Symbol("id"), id)
        OpenAPI.validate_property(ProductAddSizeChart, Symbol("url"), url)
        return new(id, url, )
    end
end # type ProductAddSizeChart

const _property_types_ProductAddSizeChart = Dict{Symbol,String}(Symbol("id")=>"String", Symbol("url")=>"String", )
OpenAPI.property_type(::Type{ ProductAddSizeChart }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ProductAddSizeChart[name]))}

function check_required(o::ProductAddSizeChart)
    true
end

function OpenAPI.validate_property(::Type{ ProductAddSizeChart }, name::Symbol, val)

    if name === Symbol("id")
        OpenAPI.validate_param(name, "ProductAddSizeChart", :minLength, val, 1)
    end

    if name === Symbol("url")
        OpenAPI.validate_param(name, "ProductAddSizeChart", :minLength, val, 1)
    end
end
