# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""CustomerGroupAdd_200_response_result

    CustomerGroupAdd200ResponseResult(;
        group_id=nothing,
    )

    - group_id::String
"""
Base.@kwdef mutable struct CustomerGroupAdd200ResponseResult <: OpenAPI.APIModel
    group_id::Union{Nothing, String} = nothing

    function CustomerGroupAdd200ResponseResult(group_id, )
        OpenAPI.validate_property(CustomerGroupAdd200ResponseResult, Symbol("group_id"), group_id)
        return new(group_id, )
    end
end # type CustomerGroupAdd200ResponseResult

const _property_types_CustomerGroupAdd200ResponseResult = Dict{Symbol,String}(Symbol("group_id")=>"String", )
OpenAPI.property_type(::Type{ CustomerGroupAdd200ResponseResult }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_CustomerGroupAdd200ResponseResult[name]))}

function check_required(o::CustomerGroupAdd200ResponseResult)
    true
end

function OpenAPI.validate_property(::Type{ CustomerGroupAdd200ResponseResult }, name::Symbol, val)

end
