# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""StoreAttribute_Group

    StoreAttributeGroup(;
        id=nothing,
        name=nothing,
        position=nothing,
        attribute_set_id=nothing,
        assigned_attribute_ids=nothing,
        additional_fields=nothing,
        custom_fields=nothing,
    )

    - id::String
    - name::String
    - position::Int64
    - attribute_set_id::String
    - assigned_attribute_ids::Vector{String}
    - additional_fields::Any
    - custom_fields::Any
"""
Base.@kwdef mutable struct StoreAttributeGroup <: OpenAPI.APIModel
    id::Union{Nothing, String} = nothing
    name::Union{Nothing, String} = nothing
    position::Union{Nothing, Int64} = nothing
    attribute_set_id::Union{Nothing, String} = nothing
    assigned_attribute_ids::Union{Nothing, Vector{String}} = nothing
    additional_fields::Union{Nothing, Any} = nothing
    custom_fields::Union{Nothing, Any} = nothing

    function StoreAttributeGroup(id, name, position, attribute_set_id, assigned_attribute_ids, additional_fields, custom_fields, )
        OpenAPI.validate_property(StoreAttributeGroup, Symbol("id"), id)
        OpenAPI.validate_property(StoreAttributeGroup, Symbol("name"), name)
        OpenAPI.validate_property(StoreAttributeGroup, Symbol("position"), position)
        OpenAPI.validate_property(StoreAttributeGroup, Symbol("attribute_set_id"), attribute_set_id)
        OpenAPI.validate_property(StoreAttributeGroup, Symbol("assigned_attribute_ids"), assigned_attribute_ids)
        OpenAPI.validate_property(StoreAttributeGroup, Symbol("additional_fields"), additional_fields)
        OpenAPI.validate_property(StoreAttributeGroup, Symbol("custom_fields"), custom_fields)
        return new(id, name, position, attribute_set_id, assigned_attribute_ids, additional_fields, custom_fields, )
    end
end # type StoreAttributeGroup

const _property_types_StoreAttributeGroup = Dict{Symbol,String}(Symbol("id")=>"String", Symbol("name")=>"String", Symbol("position")=>"Int64", Symbol("attribute_set_id")=>"String", Symbol("assigned_attribute_ids")=>"Vector{String}", Symbol("additional_fields")=>"Any", Symbol("custom_fields")=>"Any", )
OpenAPI.property_type(::Type{ StoreAttributeGroup }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_StoreAttributeGroup[name]))}

function check_required(o::StoreAttributeGroup)
    true
end

function OpenAPI.validate_property(::Type{ StoreAttributeGroup }, name::Symbol, val)







end
