# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""Order

    Order(;
        id=nothing,
        order_id=nothing,
        basket_id=nothing,
        channel_id=nothing,
        customer=nothing,
        create_at=nothing,
        currency=nothing,
        shipping_address=nothing,
        billing_address=nothing,
        payment_method=nothing,
        shipping_method=nothing,
        shipping_methods=nothing,
        status=nothing,
        totals=nothing,
        total=nothing,
        discounts=nothing,
        order_products=nothing,
        bundles=nothing,
        modified_at=nothing,
        finished_time=nothing,
        comment=nothing,
        store_id=nothing,
        warehouses_ids=nothing,
        refunds=nothing,
        gift_message=nothing,
        order_details_url=nothing,
        additional_fields=nothing,
        custom_fields=nothing,
    )

    - id::String
    - order_id::String
    - basket_id::String
    - channel_id::String
    - customer::BaseCustomer
    - create_at::A2CDateTime
    - currency::Currency
    - shipping_address::CustomerAddress
    - billing_address::CustomerAddress
    - payment_method::OrderPaymentMethod
    - shipping_method::OrderShippingMethod
    - shipping_methods::Vector{OrderShippingMethod}
    - status::OrderStatus
    - totals::OrderTotals
    - total::OrderTotal
    - discounts::Vector{OrderTotalsNewDiscount}
    - order_products::Vector{OrderItem}
    - bundles::Vector{OrderItem}
    - modified_at::A2CDateTime
    - finished_time::A2CDateTime
    - comment::String
    - store_id::String
    - warehouses_ids::Vector{String}
    - refunds::Vector{OrderRefund}
    - gift_message::String
    - order_details_url::String
    - additional_fields::Any
    - custom_fields::Any
"""
Base.@kwdef mutable struct Order <: OpenAPI.APIModel
    id::Union{Nothing, String} = nothing
    order_id::Union{Nothing, String} = nothing
    basket_id::Union{Nothing, String} = nothing
    channel_id::Union{Nothing, String} = nothing
    customer = nothing # spec type: Union{ Nothing, BaseCustomer }
    create_at = nothing # spec type: Union{ Nothing, A2CDateTime }
    currency = nothing # spec type: Union{ Nothing, Currency }
    shipping_address = nothing # spec type: Union{ Nothing, CustomerAddress }
    billing_address = nothing # spec type: Union{ Nothing, CustomerAddress }
    payment_method = nothing # spec type: Union{ Nothing, OrderPaymentMethod }
    shipping_method = nothing # spec type: Union{ Nothing, OrderShippingMethod }
    shipping_methods::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{OrderShippingMethod} }
    status = nothing # spec type: Union{ Nothing, OrderStatus }
    totals = nothing # spec type: Union{ Nothing, OrderTotals }
    total = nothing # spec type: Union{ Nothing, OrderTotal }
    discounts::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{OrderTotalsNewDiscount} }
    order_products::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{OrderItem} }
    bundles::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{OrderItem} }
    modified_at = nothing # spec type: Union{ Nothing, A2CDateTime }
    finished_time = nothing # spec type: Union{ Nothing, A2CDateTime }
    comment::Union{Nothing, String} = nothing
    store_id::Union{Nothing, String} = nothing
    warehouses_ids::Union{Nothing, Vector{String}} = nothing
    refunds::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{OrderRefund} }
    gift_message::Union{Nothing, String} = nothing
    order_details_url::Union{Nothing, String} = nothing
    additional_fields::Union{Nothing, Any} = nothing
    custom_fields::Union{Nothing, Any} = nothing

    function Order(id, order_id, basket_id, channel_id, customer, create_at, currency, shipping_address, billing_address, payment_method, shipping_method, shipping_methods, status, totals, total, discounts, order_products, bundles, modified_at, finished_time, comment, store_id, warehouses_ids, refunds, gift_message, order_details_url, additional_fields, custom_fields, )
        OpenAPI.validate_property(Order, Symbol("id"), id)
        OpenAPI.validate_property(Order, Symbol("order_id"), order_id)
        OpenAPI.validate_property(Order, Symbol("basket_id"), basket_id)
        OpenAPI.validate_property(Order, Symbol("channel_id"), channel_id)
        OpenAPI.validate_property(Order, Symbol("customer"), customer)
        OpenAPI.validate_property(Order, Symbol("create_at"), create_at)
        OpenAPI.validate_property(Order, Symbol("currency"), currency)
        OpenAPI.validate_property(Order, Symbol("shipping_address"), shipping_address)
        OpenAPI.validate_property(Order, Symbol("billing_address"), billing_address)
        OpenAPI.validate_property(Order, Symbol("payment_method"), payment_method)
        OpenAPI.validate_property(Order, Symbol("shipping_method"), shipping_method)
        OpenAPI.validate_property(Order, Symbol("shipping_methods"), shipping_methods)
        OpenAPI.validate_property(Order, Symbol("status"), status)
        OpenAPI.validate_property(Order, Symbol("totals"), totals)
        OpenAPI.validate_property(Order, Symbol("total"), total)
        OpenAPI.validate_property(Order, Symbol("discounts"), discounts)
        OpenAPI.validate_property(Order, Symbol("order_products"), order_products)
        OpenAPI.validate_property(Order, Symbol("bundles"), bundles)
        OpenAPI.validate_property(Order, Symbol("modified_at"), modified_at)
        OpenAPI.validate_property(Order, Symbol("finished_time"), finished_time)
        OpenAPI.validate_property(Order, Symbol("comment"), comment)
        OpenAPI.validate_property(Order, Symbol("store_id"), store_id)
        OpenAPI.validate_property(Order, Symbol("warehouses_ids"), warehouses_ids)
        OpenAPI.validate_property(Order, Symbol("refunds"), refunds)
        OpenAPI.validate_property(Order, Symbol("gift_message"), gift_message)
        OpenAPI.validate_property(Order, Symbol("order_details_url"), order_details_url)
        OpenAPI.validate_property(Order, Symbol("additional_fields"), additional_fields)
        OpenAPI.validate_property(Order, Symbol("custom_fields"), custom_fields)
        return new(id, order_id, basket_id, channel_id, customer, create_at, currency, shipping_address, billing_address, payment_method, shipping_method, shipping_methods, status, totals, total, discounts, order_products, bundles, modified_at, finished_time, comment, store_id, warehouses_ids, refunds, gift_message, order_details_url, additional_fields, custom_fields, )
    end
end # type Order

const _property_types_Order = Dict{Symbol,String}(Symbol("id")=>"String", Symbol("order_id")=>"String", Symbol("basket_id")=>"String", Symbol("channel_id")=>"String", Symbol("customer")=>"BaseCustomer", Symbol("create_at")=>"A2CDateTime", Symbol("currency")=>"Currency", Symbol("shipping_address")=>"CustomerAddress", Symbol("billing_address")=>"CustomerAddress", Symbol("payment_method")=>"OrderPaymentMethod", Symbol("shipping_method")=>"OrderShippingMethod", Symbol("shipping_methods")=>"Vector{OrderShippingMethod}", Symbol("status")=>"OrderStatus", Symbol("totals")=>"OrderTotals", Symbol("total")=>"OrderTotal", Symbol("discounts")=>"Vector{OrderTotalsNewDiscount}", Symbol("order_products")=>"Vector{OrderItem}", Symbol("bundles")=>"Vector{OrderItem}", Symbol("modified_at")=>"A2CDateTime", Symbol("finished_time")=>"A2CDateTime", Symbol("comment")=>"String", Symbol("store_id")=>"String", Symbol("warehouses_ids")=>"Vector{String}", Symbol("refunds")=>"Vector{OrderRefund}", Symbol("gift_message")=>"String", Symbol("order_details_url")=>"String", Symbol("additional_fields")=>"Any", Symbol("custom_fields")=>"Any", )
OpenAPI.property_type(::Type{ Order }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_Order[name]))}

function check_required(o::Order)
    true
end

function OpenAPI.validate_property(::Type{ Order }, name::Symbol, val)




























end
