# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ProductAdd_files_inner

    ProductAddFilesInner(;
        name=nothing,
        url=nothing,
    )

    - name::String
    - url::String
"""
Base.@kwdef mutable struct ProductAddFilesInner <: OpenAPI.APIModel
    name::Union{Nothing, String} = nothing
    url::Union{Nothing, String} = nothing

    function ProductAddFilesInner(name, url, )
        OpenAPI.validate_property(ProductAddFilesInner, Symbol("name"), name)
        OpenAPI.validate_property(ProductAddFilesInner, Symbol("url"), url)
        return new(name, url, )
    end
end # type ProductAddFilesInner

const _property_types_ProductAddFilesInner = Dict{Symbol,String}(Symbol("name")=>"String", Symbol("url")=>"String", )
OpenAPI.property_type(::Type{ ProductAddFilesInner }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ProductAddFilesInner[name]))}

function check_required(o::ProductAddFilesInner)
    o.name === nothing && (return false)
    o.url === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ ProductAddFilesInner }, name::Symbol, val)


end
