# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""OrderAbandoned

    OrderAbandoned(;
        id=nothing,
        customer=nothing,
        basket_id=nothing,
        basket_url=nothing,
        created_at=nothing,
        modified_at=nothing,
        currency=nothing,
        totals=nothing,
        order_products=nothing,
        additional_fields=nothing,
        custom_fields=nothing,
    )

    - id::String
    - customer::BaseCustomer
    - basket_id::String
    - basket_url::String
    - created_at::A2CDateTime
    - modified_at::A2CDateTime
    - currency::Currency
    - totals::OrderTotals
    - order_products::Vector{OrderItem}
    - additional_fields::Any
    - custom_fields::Any
"""
Base.@kwdef mutable struct OrderAbandoned <: OpenAPI.APIModel
    id::Union{Nothing, String} = nothing
    customer = nothing # spec type: Union{ Nothing, BaseCustomer }
    basket_id::Union{Nothing, String} = nothing
    basket_url::Union{Nothing, String} = nothing
    created_at = nothing # spec type: Union{ Nothing, A2CDateTime }
    modified_at = nothing # spec type: Union{ Nothing, A2CDateTime }
    currency = nothing # spec type: Union{ Nothing, Currency }
    totals = nothing # spec type: Union{ Nothing, OrderTotals }
    order_products::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{OrderItem} }
    additional_fields::Union{Nothing, Any} = nothing
    custom_fields::Union{Nothing, Any} = nothing

    function OrderAbandoned(id, customer, basket_id, basket_url, created_at, modified_at, currency, totals, order_products, additional_fields, custom_fields, )
        OpenAPI.validate_property(OrderAbandoned, Symbol("id"), id)
        OpenAPI.validate_property(OrderAbandoned, Symbol("customer"), customer)
        OpenAPI.validate_property(OrderAbandoned, Symbol("basket_id"), basket_id)
        OpenAPI.validate_property(OrderAbandoned, Symbol("basket_url"), basket_url)
        OpenAPI.validate_property(OrderAbandoned, Symbol("created_at"), created_at)
        OpenAPI.validate_property(OrderAbandoned, Symbol("modified_at"), modified_at)
        OpenAPI.validate_property(OrderAbandoned, Symbol("currency"), currency)
        OpenAPI.validate_property(OrderAbandoned, Symbol("totals"), totals)
        OpenAPI.validate_property(OrderAbandoned, Symbol("order_products"), order_products)
        OpenAPI.validate_property(OrderAbandoned, Symbol("additional_fields"), additional_fields)
        OpenAPI.validate_property(OrderAbandoned, Symbol("custom_fields"), custom_fields)
        return new(id, customer, basket_id, basket_url, created_at, modified_at, currency, totals, order_products, additional_fields, custom_fields, )
    end
end # type OrderAbandoned

const _property_types_OrderAbandoned = Dict{Symbol,String}(Symbol("id")=>"String", Symbol("customer")=>"BaseCustomer", Symbol("basket_id")=>"String", Symbol("basket_url")=>"String", Symbol("created_at")=>"A2CDateTime", Symbol("modified_at")=>"A2CDateTime", Symbol("currency")=>"Currency", Symbol("totals")=>"OrderTotals", Symbol("order_products")=>"Vector{OrderItem}", Symbol("additional_fields")=>"Any", Symbol("custom_fields")=>"Any", )
OpenAPI.property_type(::Type{ OrderAbandoned }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_OrderAbandoned[name]))}

function check_required(o::OrderAbandoned)
    true
end

function OpenAPI.validate_property(::Type{ OrderAbandoned }, name::Symbol, val)











end
