# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""CustomerDelete_200_response_result

    CustomerDelete200ResponseResult(;
        delete_items=nothing,
    )

    - delete_items::Int64
"""
Base.@kwdef mutable struct CustomerDelete200ResponseResult <: OpenAPI.APIModel
    delete_items::Union{Nothing, Int64} = nothing

    function CustomerDelete200ResponseResult(delete_items, )
        OpenAPI.validate_property(CustomerDelete200ResponseResult, Symbol("delete_items"), delete_items)
        return new(delete_items, )
    end
end # type CustomerDelete200ResponseResult

const _property_types_CustomerDelete200ResponseResult = Dict{Symbol,String}(Symbol("delete_items")=>"Int64", )
OpenAPI.property_type(::Type{ CustomerDelete200ResponseResult }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_CustomerDelete200ResponseResult[name]))}

function check_required(o::CustomerDelete200ResponseResult)
    true
end

function OpenAPI.validate_property(::Type{ CustomerDelete200ResponseResult }, name::Symbol, val)

end
