# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""Order_Status_Refund_Item

    OrderStatusRefundItem(;
        product_id=nothing,
        variant_id=nothing,
        order_product_id=nothing,
        qty=nothing,
        refund=nothing,
        additional_fields=nothing,
        custom_fields=nothing,
    )

    - product_id::String
    - variant_id::String
    - order_product_id::String
    - qty::Float64
    - refund::Float64
    - additional_fields::Any
    - custom_fields::Any
"""
Base.@kwdef mutable struct OrderStatusRefundItem <: OpenAPI.APIModel
    product_id::Union{Nothing, String} = nothing
    variant_id::Union{Nothing, String} = nothing
    order_product_id::Union{Nothing, String} = nothing
    qty::Union{Nothing, Float64} = nothing
    refund::Union{Nothing, Float64} = nothing
    additional_fields::Union{Nothing, Any} = nothing
    custom_fields::Union{Nothing, Any} = nothing

    function OrderStatusRefundItem(product_id, variant_id, order_product_id, qty, refund, additional_fields, custom_fields, )
        OpenAPI.validate_property(OrderStatusRefundItem, Symbol("product_id"), product_id)
        OpenAPI.validate_property(OrderStatusRefundItem, Symbol("variant_id"), variant_id)
        OpenAPI.validate_property(OrderStatusRefundItem, Symbol("order_product_id"), order_product_id)
        OpenAPI.validate_property(OrderStatusRefundItem, Symbol("qty"), qty)
        OpenAPI.validate_property(OrderStatusRefundItem, Symbol("refund"), refund)
        OpenAPI.validate_property(OrderStatusRefundItem, Symbol("additional_fields"), additional_fields)
        OpenAPI.validate_property(OrderStatusRefundItem, Symbol("custom_fields"), custom_fields)
        return new(product_id, variant_id, order_product_id, qty, refund, additional_fields, custom_fields, )
    end
end # type OrderStatusRefundItem

const _property_types_OrderStatusRefundItem = Dict{Symbol,String}(Symbol("product_id")=>"String", Symbol("variant_id")=>"String", Symbol("order_product_id")=>"String", Symbol("qty")=>"Float64", Symbol("refund")=>"Float64", Symbol("additional_fields")=>"Any", Symbol("custom_fields")=>"Any", )
OpenAPI.property_type(::Type{ OrderStatusRefundItem }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_OrderStatusRefundItem[name]))}

function check_required(o::OrderStatusRefundItem)
    true
end

function OpenAPI.validate_property(::Type{ OrderStatusRefundItem }, name::Symbol, val)







end
