# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""Analytics_ProductMetric

    AnalyticsProductMetric(;
        items_sold=nothing,
        orders_count=nothing,
        gross_sales=nothing,
        net_sales=nothing,
        discounts=nothing,
        refunds=nothing,
        currency_id=nothing,
        additional_fields=nothing,
        custom_fields=nothing,
    )

    - items_sold::Int64
    - orders_count::Int64
    - gross_sales::Float64
    - net_sales::Float64
    - discounts::Float64
    - refunds::Float64
    - currency_id::String
    - additional_fields::Any
    - custom_fields::Any
"""
Base.@kwdef mutable struct AnalyticsProductMetric <: OpenAPI.APIModel
    items_sold::Union{Nothing, Int64} = nothing
    orders_count::Union{Nothing, Int64} = nothing
    gross_sales::Union{Nothing, Float64} = nothing
    net_sales::Union{Nothing, Float64} = nothing
    discounts::Union{Nothing, Float64} = nothing
    refunds::Union{Nothing, Float64} = nothing
    currency_id::Union{Nothing, String} = nothing
    additional_fields::Union{Nothing, Any} = nothing
    custom_fields::Union{Nothing, Any} = nothing

    function AnalyticsProductMetric(items_sold, orders_count, gross_sales, net_sales, discounts, refunds, currency_id, additional_fields, custom_fields, )
        OpenAPI.validate_property(AnalyticsProductMetric, Symbol("items_sold"), items_sold)
        OpenAPI.validate_property(AnalyticsProductMetric, Symbol("orders_count"), orders_count)
        OpenAPI.validate_property(AnalyticsProductMetric, Symbol("gross_sales"), gross_sales)
        OpenAPI.validate_property(AnalyticsProductMetric, Symbol("net_sales"), net_sales)
        OpenAPI.validate_property(AnalyticsProductMetric, Symbol("discounts"), discounts)
        OpenAPI.validate_property(AnalyticsProductMetric, Symbol("refunds"), refunds)
        OpenAPI.validate_property(AnalyticsProductMetric, Symbol("currency_id"), currency_id)
        OpenAPI.validate_property(AnalyticsProductMetric, Symbol("additional_fields"), additional_fields)
        OpenAPI.validate_property(AnalyticsProductMetric, Symbol("custom_fields"), custom_fields)
        return new(items_sold, orders_count, gross_sales, net_sales, discounts, refunds, currency_id, additional_fields, custom_fields, )
    end
end # type AnalyticsProductMetric

const _property_types_AnalyticsProductMetric = Dict{Symbol,String}(Symbol("items_sold")=>"Int64", Symbol("orders_count")=>"Int64", Symbol("gross_sales")=>"Float64", Symbol("net_sales")=>"Float64", Symbol("discounts")=>"Float64", Symbol("refunds")=>"Float64", Symbol("currency_id")=>"String", Symbol("additional_fields")=>"Any", Symbol("custom_fields")=>"Any", )
OpenAPI.property_type(::Type{ AnalyticsProductMetric }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_AnalyticsProductMetric[name]))}

function check_required(o::AnalyticsProductMetric)
    true
end

function OpenAPI.validate_property(::Type{ AnalyticsProductMetric }, name::Symbol, val)









end
