# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""Response_Analytics_CustomerReport_Result

    ResponseAnalyticsCustomerReportResult(;
        period=nothing,
        items=nothing,
        additional_fields=nothing,
        custom_fields=nothing,
    )

    - period::AnalyticsPeriod
    - items::Vector{AnalyticsCustomer}
    - additional_fields::Any
    - custom_fields::Any
"""
Base.@kwdef mutable struct ResponseAnalyticsCustomerReportResult <: OpenAPI.APIModel
    period = nothing # spec type: Union{ Nothing, AnalyticsPeriod }
    items::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{AnalyticsCustomer} }
    additional_fields::Union{Nothing, Any} = nothing
    custom_fields::Union{Nothing, Any} = nothing

    function ResponseAnalyticsCustomerReportResult(period, items, additional_fields, custom_fields, )
        OpenAPI.validate_property(ResponseAnalyticsCustomerReportResult, Symbol("period"), period)
        OpenAPI.validate_property(ResponseAnalyticsCustomerReportResult, Symbol("items"), items)
        OpenAPI.validate_property(ResponseAnalyticsCustomerReportResult, Symbol("additional_fields"), additional_fields)
        OpenAPI.validate_property(ResponseAnalyticsCustomerReportResult, Symbol("custom_fields"), custom_fields)
        return new(period, items, additional_fields, custom_fields, )
    end
end # type ResponseAnalyticsCustomerReportResult

const _property_types_ResponseAnalyticsCustomerReportResult = Dict{Symbol,String}(Symbol("period")=>"AnalyticsPeriod", Symbol("items")=>"Vector{AnalyticsCustomer}", Symbol("additional_fields")=>"Any", Symbol("custom_fields")=>"Any", )
OpenAPI.property_type(::Type{ ResponseAnalyticsCustomerReportResult }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ResponseAnalyticsCustomerReportResult[name]))}

function check_required(o::ResponseAnalyticsCustomerReportResult)
    true
end

function OpenAPI.validate_property(::Type{ ResponseAnalyticsCustomerReportResult }, name::Symbol, val)




end
