# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""Response_Order_Abandoned_List_Result

    ResponseOrderAbandonedListResult(;
        order=nothing,
        additional_fields=nothing,
        custom_fields=nothing,
    )

    - order::Vector{OrderAbandoned}
    - additional_fields::Any
    - custom_fields::Any
"""
Base.@kwdef mutable struct ResponseOrderAbandonedListResult <: OpenAPI.APIModel
    order::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{OrderAbandoned} }
    additional_fields::Union{Nothing, Any} = nothing
    custom_fields::Union{Nothing, Any} = nothing

    function ResponseOrderAbandonedListResult(order, additional_fields, custom_fields, )
        OpenAPI.validate_property(ResponseOrderAbandonedListResult, Symbol("order"), order)
        OpenAPI.validate_property(ResponseOrderAbandonedListResult, Symbol("additional_fields"), additional_fields)
        OpenAPI.validate_property(ResponseOrderAbandonedListResult, Symbol("custom_fields"), custom_fields)
        return new(order, additional_fields, custom_fields, )
    end
end # type ResponseOrderAbandonedListResult

const _property_types_ResponseOrderAbandonedListResult = Dict{Symbol,String}(Symbol("order")=>"Vector{OrderAbandoned}", Symbol("additional_fields")=>"Any", Symbol("custom_fields")=>"Any", )
OpenAPI.property_type(::Type{ ResponseOrderAbandonedListResult }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ResponseOrderAbandonedListResult[name]))}

function check_required(o::ResponseOrderAbandonedListResult)
    true
end

function OpenAPI.validate_property(::Type{ ResponseOrderAbandonedListResult }, name::Symbol, val)



end
