# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

module APIClient

using Dates, TimeZones
using OpenAPI
using OpenAPI.Clients

const API_VERSION = "1.1"

include("modelincludes.jl")

include("apis/api_AccountApi.jl")
include("apis/api_AttributeApi.jl")
include("apis/api_BasketApi.jl")
include("apis/api_BatchApi.jl")
include("apis/api_BridgeApi.jl")
include("apis/api_CartApi.jl")
include("apis/api_CategoryApi.jl")
include("apis/api_CustomerApi.jl")
include("apis/api_MarketplaceApi.jl")
include("apis/api_OrderApi.jl")
include("apis/api_ProductApi.jl")
include("apis/api_ReturnApi.jl")
include("apis/api_SubscriberApi.jl")
include("apis/api_TaxApi.jl")
include("apis/api_WebhookApi.jl")

end # module APIClient
